/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1EventSource = require('./IoArgoprojEventsV1alpha1EventSource');

/**
 * The EventsourceEventSourceWatchEvent model module.
 * @module model/EventsourceEventSourceWatchEvent
 * @version VERSION
 */
class EventsourceEventSourceWatchEvent {
  /**
   * Constructs a new <code>EventsourceEventSourceWatchEvent</code>.
   * @alias module:model/EventsourceEventSourceWatchEvent
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EventsourceEventSourceWatchEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventsourceEventSourceWatchEvent} obj Optional instance to populate.
   * @return {module:model/EventsourceEventSourceWatchEvent} The populated <code>EventsourceEventSourceWatchEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventsourceEventSourceWatchEvent();
      if (data.hasOwnProperty('object'))
        obj._object = IoArgoprojEventsV1alpha1EventSource.constructFromObject(data['object']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoArgoprojEventsV1alpha1EventSource} _object
 */
EventsourceEventSourceWatchEvent.prototype._object = undefined;

/**
 * @member {String} type
 */
EventsourceEventSourceWatchEvent.prototype.type = undefined;

module.exports = EventsourceEventSourceWatchEvent;
