/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojWorkflowV1alpha1GCSArtifactRepository model module.
 * @module model/IoArgoprojWorkflowV1alpha1GCSArtifactRepository
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1GCSArtifactRepository {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1GCSArtifactRepository</code>.
   * GCSArtifactRepository defines the controller configuration for a GCS artifact repository
   * @alias module:model/IoArgoprojWorkflowV1alpha1GCSArtifactRepository
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1GCSArtifactRepository</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1GCSArtifactRepository} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1GCSArtifactRepository} The populated <code>IoArgoprojWorkflowV1alpha1GCSArtifactRepository</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1GCSArtifactRepository();
      if (data.hasOwnProperty('bucket'))
        obj.bucket = ApiClient.convertToType(data['bucket'], 'String');
      if (data.hasOwnProperty('keyFormat'))
        obj.keyFormat = ApiClient.convertToType(data['keyFormat'], 'String');
      if (data.hasOwnProperty('serviceAccountKeySecret'))
        obj.serviceAccountKeySecret = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['serviceAccountKeySecret']);
    }
    return obj;
  }
}

/**
 * Bucket is the name of the bucket
 * @member {String} bucket
 */
IoArgoprojWorkflowV1alpha1GCSArtifactRepository.prototype.bucket = undefined;

/**
 * KeyFormat defines the format of how to store keys and can reference workflow variables.
 * @member {String} keyFormat
 */
IoArgoprojWorkflowV1alpha1GCSArtifactRepository.prototype.keyFormat = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} serviceAccountKeySecret
 */
IoArgoprojWorkflowV1alpha1GCSArtifactRepository.prototype.serviceAccountKeySecret = undefined;

module.exports = IoArgoprojWorkflowV1alpha1GCSArtifactRepository;
