/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1HTTPAuth = require('./IoArgoprojWorkflowV1alpha1HTTPAuth');
const IoArgoprojWorkflowV1alpha1Header = require('./IoArgoprojWorkflowV1alpha1Header');

/**
 * The IoArgoprojWorkflowV1alpha1HTTPArtifact model module.
 * @module model/IoArgoprojWorkflowV1alpha1HTTPArtifact
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1HTTPArtifact {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1HTTPArtifact</code>.
   * HTTPArtifact allows a file served on HTTP to be placed as an input artifact in a container
   * @alias module:model/IoArgoprojWorkflowV1alpha1HTTPArtifact
   * @class
   * @param url {String} URL of the artifact
   */
  constructor(url) {
    this.url = url;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1HTTPArtifact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1HTTPArtifact} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1HTTPArtifact} The populated <code>IoArgoprojWorkflowV1alpha1HTTPArtifact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1HTTPArtifact();
      if (data.hasOwnProperty('auth'))
        obj.auth = IoArgoprojWorkflowV1alpha1HTTPAuth.constructFromObject(data['auth']);
      if (data.hasOwnProperty('headers'))
        obj.headers = ApiClient.convertToType(data['headers'], [IoArgoprojWorkflowV1alpha1Header]);
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1HTTPAuth} auth
 */
IoArgoprojWorkflowV1alpha1HTTPArtifact.prototype.auth = undefined;

/**
 * Headers are an optional list of headers to send with HTTP requests for artifacts
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1Header>} headers
 */
IoArgoprojWorkflowV1alpha1HTTPArtifact.prototype.headers = undefined;

/**
 * URL of the artifact
 * @member {String} url
 */
IoArgoprojWorkflowV1alpha1HTTPArtifact.prototype.url = undefined;

module.exports = IoArgoprojWorkflowV1alpha1HTTPArtifact;
