/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1TriggerParameter = require('./IoArgoprojEventsV1alpha1TriggerParameter');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1OpenWhiskTrigger model module.
 * @module model/IoArgoprojEventsV1alpha1OpenWhiskTrigger
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1OpenWhiskTrigger {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1OpenWhiskTrigger</code>.
   * OpenWhiskTrigger refers to the specification of the OpenWhisk trigger.
   * @alias module:model/IoArgoprojEventsV1alpha1OpenWhiskTrigger
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1OpenWhiskTrigger</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1OpenWhiskTrigger} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1OpenWhiskTrigger} The populated <code>IoArgoprojEventsV1alpha1OpenWhiskTrigger</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1OpenWhiskTrigger();
      if (data.hasOwnProperty('actionName'))
        obj.actionName = ApiClient.convertToType(data['actionName'], 'String');
      if (data.hasOwnProperty('authToken'))
        obj.authToken = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['authToken']);
      if (data.hasOwnProperty('host'))
        obj.host = ApiClient.convertToType(data['host'], 'String');
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], [IoArgoprojEventsV1alpha1TriggerParameter]);
      if (data.hasOwnProperty('payload'))
        obj.payload = ApiClient.convertToType(data['payload'], [IoArgoprojEventsV1alpha1TriggerParameter]);
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
    }
    return obj;
  }
}

/**
 * Name of the action/function.
 * @member {String} actionName
 */
module.exports.actionName = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} authToken
 */
module.exports.authToken = undefined;

/**
 * Host URL of the OpenWhisk.
 * @member {String} host
 */
module.exports.host = undefined;

/**
 * Namespace for the action. Defaults to \"_\". +optional.
 * @member {String} namespace
 */
module.exports.namespace = undefined;

/**
 * @member {Array.<module:model/IoArgoprojEventsV1alpha1TriggerParameter>} parameters
 */
module.exports.parameters = undefined;

/**
 * Payload is the list of key-value extracted from an event payload to construct the request payload.
 * @member {Array.<module:model/IoArgoprojEventsV1alpha1TriggerParameter>} payload
 */
module.exports.payload = undefined;

/**
 * @member {String} version
 */
module.exports.version = undefined;

module.exports = IoArgoprojEventsV1alpha1OpenWhiskTrigger;
