/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1EventDependencyTransformer model module.
 * @module model/IoArgoprojEventsV1alpha1EventDependencyTransformer
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1EventDependencyTransformer {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1EventDependencyTransformer</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1EventDependencyTransformer
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1EventDependencyTransformer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1EventDependencyTransformer} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1EventDependencyTransformer} The populated <code>IoArgoprojEventsV1alpha1EventDependencyTransformer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1EventDependencyTransformer();
      if (data.hasOwnProperty('jq'))
        obj.jq = ApiClient.convertToType(data['jq'], 'String');
      if (data.hasOwnProperty('script'))
        obj.script = ApiClient.convertToType(data['script'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} jq
 */
module.exports.jq = undefined;

/**
 * @member {String} script
 */
module.exports.script = undefined;

module.exports = IoArgoprojEventsV1alpha1EventDependencyTransformer;
