/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1OAuth2EndpointParam model module.
 * @module model/IoArgoprojWorkflowV1alpha1OAuth2EndpointParam
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1OAuth2EndpointParam {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1OAuth2EndpointParam</code>.
   * EndpointParam is for requesting optional fields that should be sent in the oauth request
   * @alias module:model/IoArgoprojWorkflowV1alpha1OAuth2EndpointParam
   * @class
   * @param key {String} Name is the header name
   */
  constructor(key) {
    this.key = key;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1OAuth2EndpointParam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1OAuth2EndpointParam} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1OAuth2EndpointParam} The populated <code>IoArgoprojWorkflowV1alpha1OAuth2EndpointParam</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1OAuth2EndpointParam();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * Name is the header name
 * @member {String} key
 */
IoArgoprojWorkflowV1alpha1OAuth2EndpointParam.prototype.key = undefined;

/**
 * Value is the literal value to use for the header
 * @member {String} value
 */
IoArgoprojWorkflowV1alpha1OAuth2EndpointParam.prototype.value = undefined;

module.exports = IoArgoprojWorkflowV1alpha1OAuth2EndpointParam;
