/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApimachineryPkgUtilIntstrIntOrString = require('./IoK8sApimachineryPkgUtilIntstrIntOrString');

/**
 * The IoArgoprojWorkflowV1alpha1Backoff model module.
 * @module model/IoArgoprojWorkflowV1alpha1Backoff
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1Backoff {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1Backoff</code>.
   * Backoff is a backoff strategy to use within retryStrategy
   * @alias module:model/IoArgoprojWorkflowV1alpha1Backoff
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1Backoff</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1Backoff} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1Backoff} The populated <code>IoArgoprojWorkflowV1alpha1Backoff</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1Backoff();
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'String');
      if (data.hasOwnProperty('factor'))
        obj.factor = IoK8sApimachineryPkgUtilIntstrIntOrString.constructFromObject(data['factor']);
      if (data.hasOwnProperty('maxDuration'))
        obj.maxDuration = ApiClient.convertToType(data['maxDuration'], 'String');
    }
    return obj;
  }
}

/**
 * Duration is the amount to back off. Default unit is seconds, but could also be a duration (e.g. \"2m\", \"1h\")
 * @member {String} duration
 */
IoArgoprojWorkflowV1alpha1Backoff.prototype.duration = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgUtilIntstrIntOrString} factor
 */
IoArgoprojWorkflowV1alpha1Backoff.prototype.factor = undefined;

/**
 * MaxDuration is the maximum amount of time allowed for a workflow in the backoff strategy. It is important to note that if the workflow template includes activeDeadlineSeconds, the pod's deadline is initially set with activeDeadlineSeconds. However, when the workflow fails, the pod's deadline is then overridden by maxDuration. This ensures that the workflow does not exceed the specified maximum duration when retries are involved.
 * @member {String} maxDuration
 */
IoArgoprojWorkflowV1alpha1Backoff.prototype.maxDuration = undefined;

module.exports = IoArgoprojWorkflowV1alpha1Backoff;
