/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1ContainerPort = require('./IoK8sApiCoreV1ContainerPort');
const IoK8sApiCoreV1ContainerResizePolicy = require('./IoK8sApiCoreV1ContainerResizePolicy');
const IoK8sApiCoreV1EnvFromSource = require('./IoK8sApiCoreV1EnvFromSource');
const IoK8sApiCoreV1EnvVar = require('./IoK8sApiCoreV1EnvVar');
const IoK8sApiCoreV1Lifecycle = require('./IoK8sApiCoreV1Lifecycle');
const IoK8sApiCoreV1Probe = require('./IoK8sApiCoreV1Probe');
const IoK8sApiCoreV1ResourceRequirements = require('./IoK8sApiCoreV1ResourceRequirements');
const IoK8sApiCoreV1SecurityContext = require('./IoK8sApiCoreV1SecurityContext');
const IoK8sApiCoreV1VolumeDevice = require('./IoK8sApiCoreV1VolumeDevice');
const IoK8sApiCoreV1VolumeMount = require('./IoK8sApiCoreV1VolumeMount');

/**
 * The IoArgoprojWorkflowV1alpha1UserContainer model module.
 * @module model/IoArgoprojWorkflowV1alpha1UserContainer
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1UserContainer {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1UserContainer</code>.
   * UserContainer is a container specified by a user.
   * @alias module:model/IoArgoprojWorkflowV1alpha1UserContainer
   * @class
   * @param name {String} Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1UserContainer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1UserContainer} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1UserContainer} The populated <code>IoArgoprojWorkflowV1alpha1UserContainer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1UserContainer();
      if (data.hasOwnProperty('args'))
        obj.args = ApiClient.convertToType(data['args'], ['String']);
      if (data.hasOwnProperty('command'))
        obj.command = ApiClient.convertToType(data['command'], ['String']);
      if (data.hasOwnProperty('env'))
        obj.env = ApiClient.convertToType(data['env'], [IoK8sApiCoreV1EnvVar]);
      if (data.hasOwnProperty('envFrom'))
        obj.envFrom = ApiClient.convertToType(data['envFrom'], [IoK8sApiCoreV1EnvFromSource]);
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('imagePullPolicy'))
        obj.imagePullPolicy = ApiClient.convertToType(data['imagePullPolicy'], 'String');
      if (data.hasOwnProperty('lifecycle'))
        obj.lifecycle = IoK8sApiCoreV1Lifecycle.constructFromObject(data['lifecycle']);
      if (data.hasOwnProperty('livenessProbe'))
        obj.livenessProbe = IoK8sApiCoreV1Probe.constructFromObject(data['livenessProbe']);
      if (data.hasOwnProperty('mirrorVolumeMounts'))
        obj.mirrorVolumeMounts = ApiClient.convertToType(data['mirrorVolumeMounts'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('ports'))
        obj.ports = ApiClient.convertToType(data['ports'], [IoK8sApiCoreV1ContainerPort]);
      if (data.hasOwnProperty('readinessProbe'))
        obj.readinessProbe = IoK8sApiCoreV1Probe.constructFromObject(data['readinessProbe']);
      if (data.hasOwnProperty('resizePolicy'))
        obj.resizePolicy = ApiClient.convertToType(data['resizePolicy'], [IoK8sApiCoreV1ContainerResizePolicy]);
      if (data.hasOwnProperty('resources'))
        obj.resources = IoK8sApiCoreV1ResourceRequirements.constructFromObject(data['resources']);
      if (data.hasOwnProperty('restartPolicy'))
        obj.restartPolicy = ApiClient.convertToType(data['restartPolicy'], 'String');
      if (data.hasOwnProperty('securityContext'))
        obj.securityContext = IoK8sApiCoreV1SecurityContext.constructFromObject(data['securityContext']);
      if (data.hasOwnProperty('startupProbe'))
        obj.startupProbe = IoK8sApiCoreV1Probe.constructFromObject(data['startupProbe']);
      if (data.hasOwnProperty('stdin'))
        obj.stdin = ApiClient.convertToType(data['stdin'], 'Boolean');
      if (data.hasOwnProperty('stdinOnce'))
        obj.stdinOnce = ApiClient.convertToType(data['stdinOnce'], 'Boolean');
      if (data.hasOwnProperty('terminationMessagePath'))
        obj.terminationMessagePath = ApiClient.convertToType(data['terminationMessagePath'], 'String');
      if (data.hasOwnProperty('terminationMessagePolicy'))
        obj.terminationMessagePolicy = ApiClient.convertToType(data['terminationMessagePolicy'], 'String');
      if (data.hasOwnProperty('tty'))
        obj.tty = ApiClient.convertToType(data['tty'], 'Boolean');
      if (data.hasOwnProperty('volumeDevices'))
        obj.volumeDevices = ApiClient.convertToType(data['volumeDevices'], [IoK8sApiCoreV1VolumeDevice]);
      if (data.hasOwnProperty('volumeMounts'))
        obj.volumeMounts = ApiClient.convertToType(data['volumeMounts'], [IoK8sApiCoreV1VolumeMount]);
      if (data.hasOwnProperty('workingDir'))
        obj.workingDir = ApiClient.convertToType(data['workingDir'], 'String');
    }
    return obj;
  }
}

/**
 * Arguments to the entrypoint. The container image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
 * @member {Array.<String>} args
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.args = undefined;

/**
 * Entrypoint array. Not executed within a shell. The container image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
 * @member {Array.<String>} command
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.command = undefined;

/**
 * List of environment variables to set in the container. Cannot be updated.
 * @member {Array.<module:model/IoK8sApiCoreV1EnvVar>} env
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.env = undefined;

/**
 * List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.
 * @member {Array.<module:model/IoK8sApiCoreV1EnvFromSource>} envFrom
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.envFrom = undefined;

/**
 * Container image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.
 * @member {String} image
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.image = undefined;

/**
 * Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images
 * @member {String} imagePullPolicy
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.imagePullPolicy = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1Lifecycle} lifecycle
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.lifecycle = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1Probe} livenessProbe
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.livenessProbe = undefined;

/**
 * MirrorVolumeMounts will mount the same volumes specified in the main container to the container (including artifacts), at the same mountPaths. This enables dind daemon to partially see the same filesystem as the main container in order to use features such as docker volume binding
 * @member {Boolean} mirrorVolumeMounts
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.mirrorVolumeMounts = undefined;

/**
 * Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.
 * @member {String} name
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.name = undefined;

/**
 * List of ports to expose from the container. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \"0.0.0.0\" address inside a container will be accessible from the network. Modifying this array with strategic merge patch may corrupt the data. For more information See https://github.com/kubernetes/kubernetes/issues/108255. Cannot be updated.
 * @member {Array.<module:model/IoK8sApiCoreV1ContainerPort>} ports
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.ports = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1Probe} readinessProbe
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.readinessProbe = undefined;

/**
 * Resources resize policy for the container.
 * @member {Array.<module:model/IoK8sApiCoreV1ContainerResizePolicy>} resizePolicy
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.resizePolicy = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1ResourceRequirements} resources
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.resources = undefined;

/**
 * RestartPolicy defines the restart behavior of individual containers in a pod. This field may only be set for init containers, and the only allowed value is \"Always\". For non-init containers or when this field is not specified, the restart behavior is defined by the Pod's restart policy and the container type. Setting the RestartPolicy as \"Always\" for the init container will have the following effect: this init container will be continually restarted on exit until all regular containers have terminated. Once all regular containers have completed, all init containers with restartPolicy \"Always\" will be shut down. This lifecycle differs from normal init containers and is often referred to as a \"sidecar\" container. Although this init container still starts in the init container sequence, it does not wait for the container to complete before proceeding to the next init container. Instead, the next init container starts immediately after this init container is started, or after any startupProbe has successfully completed.
 * @member {String} restartPolicy
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.restartPolicy = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecurityContext} securityContext
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.securityContext = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1Probe} startupProbe
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.startupProbe = undefined;

/**
 * Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.
 * @member {Boolean} stdin
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.stdin = undefined;

/**
 * Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false
 * @member {Boolean} stdinOnce
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.stdinOnce = undefined;

/**
 * Optional: Path at which the file to which the container's termination message will be written is mounted into the container's filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.
 * @member {String} terminationMessagePath
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.terminationMessagePath = undefined;

/**
 * Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.
 * @member {String} terminationMessagePolicy
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.terminationMessagePolicy = undefined;

/**
 * Whether this container should allocate a TTY for itself, also requires 'stdin' to be true. Default is false.
 * @member {Boolean} tty
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.tty = undefined;

/**
 * volumeDevices is the list of block devices to be used by the container.
 * @member {Array.<module:model/IoK8sApiCoreV1VolumeDevice>} volumeDevices
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.volumeDevices = undefined;

/**
 * Pod volumes to mount into the container's filesystem. Cannot be updated.
 * @member {Array.<module:model/IoK8sApiCoreV1VolumeMount>} volumeMounts
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.volumeMounts = undefined;

/**
 * Container's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.
 * @member {String} workingDir
 */
IoArgoprojWorkflowV1alpha1UserContainer.prototype.workingDir = undefined;

module.exports = IoArgoprojWorkflowV1alpha1UserContainer;
