/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1OSSLifecycleRule = require('./IoArgoprojWorkflowV1alpha1OSSLifecycleRule');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojWorkflowV1alpha1OSSArtifact model module.
 * @module model/IoArgoprojWorkflowV1alpha1OSSArtifact
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1OSSArtifact {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1OSSArtifact</code>.
   * OSSArtifact is the location of an Alibaba Cloud OSS artifact
   * @alias module:model/IoArgoprojWorkflowV1alpha1OSSArtifact
   * @class
   * @param key {String} Key is the path in the bucket where the artifact resides
   */
  constructor(key) {
    this.key = key;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1OSSArtifact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1OSSArtifact} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1OSSArtifact} The populated <code>IoArgoprojWorkflowV1alpha1OSSArtifact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1OSSArtifact();
      if (data.hasOwnProperty('accessKeySecret'))
        obj.accessKeySecret = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['accessKeySecret']);
      if (data.hasOwnProperty('bucket'))
        obj.bucket = ApiClient.convertToType(data['bucket'], 'String');
      if (data.hasOwnProperty('createBucketIfNotPresent'))
        obj.createBucketIfNotPresent = ApiClient.convertToType(data['createBucketIfNotPresent'], 'Boolean');
      if (data.hasOwnProperty('endpoint'))
        obj.endpoint = ApiClient.convertToType(data['endpoint'], 'String');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('lifecycleRule'))
        obj.lifecycleRule = IoArgoprojWorkflowV1alpha1OSSLifecycleRule.constructFromObject(data['lifecycleRule']);
      if (data.hasOwnProperty('secretKeySecret'))
        obj.secretKeySecret = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['secretKeySecret']);
      if (data.hasOwnProperty('securityToken'))
        obj.securityToken = ApiClient.convertToType(data['securityToken'], 'String');
      if (data.hasOwnProperty('useSDKCreds'))
        obj.useSDKCreds = ApiClient.convertToType(data['useSDKCreds'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} accessKeySecret
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.accessKeySecret = undefined;

/**
 * Bucket is the name of the bucket
 * @member {String} bucket
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.bucket = undefined;

/**
 * CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output artifacts, if it doesn't exist
 * @member {Boolean} createBucketIfNotPresent
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.createBucketIfNotPresent = undefined;

/**
 * Endpoint is the hostname of the bucket endpoint
 * @member {String} endpoint
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.endpoint = undefined;

/**
 * Key is the path in the bucket where the artifact resides
 * @member {String} key
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.key = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1OSSLifecycleRule} lifecycleRule
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.lifecycleRule = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} secretKeySecret
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.secretKeySecret = undefined;

/**
 * SecurityToken is the user's temporary security token. For more details, check out: https://www.alibabacloud.com/help/doc-detail/100624.htm
 * @member {String} securityToken
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.securityToken = undefined;

/**
 * UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
 * @member {Boolean} useSDKCreds
 */
IoArgoprojWorkflowV1alpha1OSSArtifact.prototype.useSDKCreds = undefined;

module.exports = IoArgoprojWorkflowV1alpha1OSSArtifact;
