/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1HTTPBodySource model module.
 * @module model/IoArgoprojWorkflowV1alpha1HTTPBodySource
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1HTTPBodySource {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1HTTPBodySource</code>.
   * HTTPBodySource contains the source of the HTTP body.
   * @alias module:model/IoArgoprojWorkflowV1alpha1HTTPBodySource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1HTTPBodySource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1HTTPBodySource} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1HTTPBodySource} The populated <code>IoArgoprojWorkflowV1alpha1HTTPBodySource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1HTTPBodySource();
      if (data.hasOwnProperty('bytes'))
        obj.bytes = ApiClient.convertToType(data['bytes'], 'Blob');
    }
    return obj;
  }
}

/**
 * @member {Blob} bytes
 */
IoArgoprojWorkflowV1alpha1HTTPBodySource.prototype.bytes = undefined;

module.exports = IoArgoprojWorkflowV1alpha1HTTPBodySource;
