/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1Backoff = require('./IoArgoprojEventsV1alpha1Backoff');
const IoArgoprojEventsV1alpha1EventSourceFilter = require('./IoArgoprojEventsV1alpha1EventSourceFilter');
const IoArgoprojEventsV1alpha1TLSConfig = require('./IoArgoprojEventsV1alpha1TLSConfig');

/**
 * The IoArgoprojEventsV1alpha1NSQEventSource model module.
 * @module model/IoArgoprojEventsV1alpha1NSQEventSource
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1NSQEventSource {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1NSQEventSource</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1NSQEventSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1NSQEventSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1NSQEventSource} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1NSQEventSource} The populated <code>IoArgoprojEventsV1alpha1NSQEventSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1NSQEventSource();
      if (data.hasOwnProperty('channel'))
        obj.channel = ApiClient.convertToType(data['channel'], 'String');
      if (data.hasOwnProperty('connectionBackoff'))
        obj.connectionBackoff = IoArgoprojEventsV1alpha1Backoff.constructFromObject(data['connectionBackoff']);
      if (data.hasOwnProperty('filter'))
        obj.filter = IoArgoprojEventsV1alpha1EventSourceFilter.constructFromObject(data['filter']);
      if (data.hasOwnProperty('hostAddress'))
        obj.hostAddress = ApiClient.convertToType(data['hostAddress'], 'String');
      if (data.hasOwnProperty('jsonBody'))
        obj.jsonBody = ApiClient.convertToType(data['jsonBody'], 'Boolean');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], {'String': 'String'});
      if (data.hasOwnProperty('tls'))
        obj.tls = IoArgoprojEventsV1alpha1TLSConfig.constructFromObject(data['tls']);
      if (data.hasOwnProperty('topic'))
        obj.topic = ApiClient.convertToType(data['topic'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} channel
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.channel = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1Backoff} connectionBackoff
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.connectionBackoff = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1EventSourceFilter} filter
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.filter = undefined;

/**
 * @member {String} hostAddress
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.hostAddress = undefined;

/**
 * @member {Boolean} jsonBody
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.jsonBody = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.metadata = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1TLSConfig} tls
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.tls = undefined;

/**
 * Topic to subscribe to.
 * @member {String} topic
 */
IoArgoprojEventsV1alpha1NSQEventSource.prototype.topic = undefined;

module.exports = IoArgoprojEventsV1alpha1NSQEventSource;
