/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1TriggerParameter = require('./IoArgoprojEventsV1alpha1TriggerParameter');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1EmailTrigger model module.
 * @module model/IoArgoprojEventsV1alpha1EmailTrigger
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1EmailTrigger {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1EmailTrigger</code>.
   * EmailTrigger refers to the specification of the email notification trigger.
   * @alias module:model/IoArgoprojEventsV1alpha1EmailTrigger
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1EmailTrigger</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1EmailTrigger} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1EmailTrigger} The populated <code>IoArgoprojEventsV1alpha1EmailTrigger</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1EmailTrigger();
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'String');
      if (data.hasOwnProperty('host'))
        obj.host = ApiClient.convertToType(data['host'], 'String');
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], [IoArgoprojEventsV1alpha1TriggerParameter]);
      if (data.hasOwnProperty('port'))
        obj.port = ApiClient.convertToType(data['port'], 'Number');
      if (data.hasOwnProperty('smtpPassword'))
        obj.smtpPassword = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['smtpPassword']);
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], ['String']);
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} body
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.body = undefined;

/**
 * @member {String} from
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.from = undefined;

/**
 * Host refers to the smtp host url to which email is send.
 * @member {String} host
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.host = undefined;

/**
 * @member {Array.<module:model/IoArgoprojEventsV1alpha1TriggerParameter>} parameters
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.parameters = undefined;

/**
 * @member {Number} port
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.port = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} smtpPassword
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.smtpPassword = undefined;

/**
 * @member {String} subject
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.subject = undefined;

/**
 * @member {Array.<String>} to
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.to = undefined;

/**
 * @member {String} username
 */
IoArgoprojEventsV1alpha1EmailTrigger.prototype.username = undefined;

module.exports = IoArgoprojEventsV1alpha1EmailTrigger;
