/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1FileArtifact model module.
 * @module model/IoArgoprojEventsV1alpha1FileArtifact
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1FileArtifact {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1FileArtifact</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1FileArtifact
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1FileArtifact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1FileArtifact} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1FileArtifact} The populated <code>IoArgoprojEventsV1alpha1FileArtifact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1FileArtifact();
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} path
 */
IoArgoprojEventsV1alpha1FileArtifact.prototype.path = undefined;

module.exports = IoArgoprojEventsV1alpha1FileArtifact;
