/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1TriggerParameterSource = require('./IoArgoprojEventsV1alpha1TriggerParameterSource');

/**
 * The IoArgoprojEventsV1alpha1TriggerParameter model module.
 * @module model/IoArgoprojEventsV1alpha1TriggerParameter
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1TriggerParameter {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1TriggerParameter</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1TriggerParameter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1TriggerParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1TriggerParameter} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1TriggerParameter} The populated <code>IoArgoprojEventsV1alpha1TriggerParameter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1TriggerParameter();
      if (data.hasOwnProperty('dest'))
        obj.dest = ApiClient.convertToType(data['dest'], 'String');
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('src'))
        obj.src = IoArgoprojEventsV1alpha1TriggerParameterSource.constructFromObject(data['src']);
    }
    return obj;
  }
}

/**
 * Dest is the JSONPath of a resource key. A path is a series of keys separated by a dot. The colon character can be escaped with '.' The -1 key can be used to append a value to an existing array. See https://github.com/tidwall/sjson#path-syntax for more information about how this is used.
 * @member {String} dest
 */
IoArgoprojEventsV1alpha1TriggerParameter.prototype.dest = undefined;

/**
 * Operation is what to do with the existing value at Dest, whether to 'prepend', 'overwrite', or 'append' it.
 * @member {String} operation
 */
IoArgoprojEventsV1alpha1TriggerParameter.prototype.operation = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1TriggerParameterSource} src
 */
IoArgoprojEventsV1alpha1TriggerParameter.prototype.src = undefined;

module.exports = IoArgoprojEventsV1alpha1TriggerParameter;
