/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1AMQPConsumeConfig model module.
 * @module model/IoArgoprojEventsV1alpha1AMQPConsumeConfig
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1AMQPConsumeConfig {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1AMQPConsumeConfig</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1AMQPConsumeConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1AMQPConsumeConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1AMQPConsumeConfig} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1AMQPConsumeConfig} The populated <code>IoArgoprojEventsV1alpha1AMQPConsumeConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1AMQPConsumeConfig();
      if (data.hasOwnProperty('autoAck'))
        obj.autoAck = ApiClient.convertToType(data['autoAck'], 'Boolean');
      if (data.hasOwnProperty('consumerTag'))
        obj.consumerTag = ApiClient.convertToType(data['consumerTag'], 'String');
      if (data.hasOwnProperty('exclusive'))
        obj.exclusive = ApiClient.convertToType(data['exclusive'], 'Boolean');
      if (data.hasOwnProperty('noLocal'))
        obj.noLocal = ApiClient.convertToType(data['noLocal'], 'Boolean');
      if (data.hasOwnProperty('noWait'))
        obj.noWait = ApiClient.convertToType(data['noWait'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} autoAck
 */
IoArgoprojEventsV1alpha1AMQPConsumeConfig.prototype.autoAck = undefined;

/**
 * @member {String} consumerTag
 */
IoArgoprojEventsV1alpha1AMQPConsumeConfig.prototype.consumerTag = undefined;

/**
 * @member {Boolean} exclusive
 */
IoArgoprojEventsV1alpha1AMQPConsumeConfig.prototype.exclusive = undefined;

/**
 * @member {Boolean} noLocal
 */
IoArgoprojEventsV1alpha1AMQPConsumeConfig.prototype.noLocal = undefined;

/**
 * @member {Boolean} noWait
 */
IoArgoprojEventsV1alpha1AMQPConsumeConfig.prototype.noWait = undefined;

module.exports = IoArgoprojEventsV1alpha1AMQPConsumeConfig;
