/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1Backoff = require('./IoArgoprojEventsV1alpha1Backoff');

/**
 * The IoArgoprojEventsV1alpha1K8SResourcePolicy model module.
 * @module model/IoArgoprojEventsV1alpha1K8SResourcePolicy
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1K8SResourcePolicy {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1K8SResourcePolicy</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1K8SResourcePolicy
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1K8SResourcePolicy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1K8SResourcePolicy} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1K8SResourcePolicy} The populated <code>IoArgoprojEventsV1alpha1K8SResourcePolicy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1K8SResourcePolicy();
      if (data.hasOwnProperty('backoff'))
        obj.backoff = IoArgoprojEventsV1alpha1Backoff.constructFromObject(data['backoff']);
      if (data.hasOwnProperty('errorOnBackoffTimeout'))
        obj.errorOnBackoffTimeout = ApiClient.convertToType(data['errorOnBackoffTimeout'], 'Boolean');
      if (data.hasOwnProperty('labels'))
        obj.labels = ApiClient.convertToType(data['labels'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * @member {module:model/IoArgoprojEventsV1alpha1Backoff} backoff
 */
IoArgoprojEventsV1alpha1K8SResourcePolicy.prototype.backoff = undefined;

/**
 * @member {Boolean} errorOnBackoffTimeout
 */
IoArgoprojEventsV1alpha1K8SResourcePolicy.prototype.errorOnBackoffTimeout = undefined;

/**
 * @member {Object.<String, String>} labels
 */
IoArgoprojEventsV1alpha1K8SResourcePolicy.prototype.labels = undefined;

module.exports = IoArgoprojEventsV1alpha1K8SResourcePolicy;
