/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1EventSourceFilter = require('./IoArgoprojEventsV1alpha1EventSourceFilter');
const IoArgoprojEventsV1alpha1TLSConfig = require('./IoArgoprojEventsV1alpha1TLSConfig');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1RedisEventSource model module.
 * @module model/IoArgoprojEventsV1alpha1RedisEventSource
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1RedisEventSource {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1RedisEventSource</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1RedisEventSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1RedisEventSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1RedisEventSource} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1RedisEventSource} The populated <code>IoArgoprojEventsV1alpha1RedisEventSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1RedisEventSource();
      if (data.hasOwnProperty('channels'))
        obj.channels = ApiClient.convertToType(data['channels'], ['String']);
      if (data.hasOwnProperty('db'))
        obj.db = ApiClient.convertToType(data['db'], 'Number');
      if (data.hasOwnProperty('filter'))
        obj.filter = IoArgoprojEventsV1alpha1EventSourceFilter.constructFromObject(data['filter']);
      if (data.hasOwnProperty('hostAddress'))
        obj.hostAddress = ApiClient.convertToType(data['hostAddress'], 'String');
      if (data.hasOwnProperty('jsonBody'))
        obj.jsonBody = ApiClient.convertToType(data['jsonBody'], 'Boolean');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], {'String': 'String'});
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['password']);
      if (data.hasOwnProperty('tls'))
        obj.tls = IoArgoprojEventsV1alpha1TLSConfig.constructFromObject(data['tls']);
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} channels
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.channels = undefined;

/**
 * @member {Number} db
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.db = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1EventSourceFilter} filter
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.filter = undefined;

/**
 * @member {String} hostAddress
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.hostAddress = undefined;

/**
 * @member {Boolean} jsonBody
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.jsonBody = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.metadata = undefined;

/**
 * @member {String} namespace
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.namespace = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} password
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.password = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1TLSConfig} tls
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.tls = undefined;

/**
 * @member {String} username
 */
IoArgoprojEventsV1alpha1RedisEventSource.prototype.username = undefined;

module.exports = IoArgoprojEventsV1alpha1RedisEventSource;
