/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1GetUserInfoResponse model module.
 * @module model/IoArgoprojWorkflowV1alpha1GetUserInfoResponse
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1GetUserInfoResponse {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1GetUserInfoResponse</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1GetUserInfoResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1GetUserInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1GetUserInfoResponse} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1GetUserInfoResponse} The populated <code>IoArgoprojWorkflowV1alpha1GetUserInfoResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1GetUserInfoResponse();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('emailVerified'))
        obj.emailVerified = ApiClient.convertToType(data['emailVerified'], 'Boolean');
      if (data.hasOwnProperty('groups'))
        obj.groups = ApiClient.convertToType(data['groups'], ['String']);
      if (data.hasOwnProperty('issuer'))
        obj.issuer = ApiClient.convertToType(data['issuer'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('serviceAccountName'))
        obj.serviceAccountName = ApiClient.convertToType(data['serviceAccountName'], 'String');
      if (data.hasOwnProperty('serviceAccountNamespace'))
        obj.serviceAccountNamespace = ApiClient.convertToType(data['serviceAccountNamespace'], 'String');
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.email = undefined;

/**
 * @member {Boolean} emailVerified
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.emailVerified = undefined;

/**
 * @member {Array.<String>} groups
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.groups = undefined;

/**
 * @member {String} issuer
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.issuer = undefined;

/**
 * @member {String} name
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.name = undefined;

/**
 * @member {String} serviceAccountName
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.serviceAccountName = undefined;

/**
 * @member {String} serviceAccountNamespace
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.serviceAccountNamespace = undefined;

/**
 * @member {String} subject
 */
IoArgoprojWorkflowV1alpha1GetUserInfoResponse.prototype.subject = undefined;

module.exports = IoArgoprojWorkflowV1alpha1GetUserInfoResponse;
