/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1Event = require('./IoArgoprojWorkflowV1alpha1Event');
const IoArgoprojWorkflowV1alpha1Submit = require('./IoArgoprojWorkflowV1alpha1Submit');

/**
 * The IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec model module.
 * @module model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec
   * @class
   * @param event {module:model/IoArgoprojWorkflowV1alpha1Event} 
   */
  constructor(event) {
    this.event = event;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec} The populated <code>IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec();
      if (data.hasOwnProperty('event'))
        obj.event = IoArgoprojWorkflowV1alpha1Event.constructFromObject(data['event']);
      if (data.hasOwnProperty('submit'))
        obj.submit = IoArgoprojWorkflowV1alpha1Submit.constructFromObject(data['submit']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1Event} event
 */
IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec.prototype.event = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1Submit} submit
 */
IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec.prototype.submit = undefined;

module.exports = IoArgoprojWorkflowV1alpha1WorkflowEventBindingSpec;
