/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1LogEntry model module.
 * @module model/IoArgoprojWorkflowV1alpha1LogEntry
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1LogEntry {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1LogEntry</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1LogEntry
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1LogEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1LogEntry} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1LogEntry} The populated <code>IoArgoprojWorkflowV1alpha1LogEntry</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1LogEntry();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('podName'))
        obj.podName = ApiClient.convertToType(data['podName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} content
 */
IoArgoprojWorkflowV1alpha1LogEntry.prototype.content = undefined;

/**
 * @member {String} podName
 */
IoArgoprojWorkflowV1alpha1LogEntry.prototype.podName = undefined;

module.exports = IoArgoprojWorkflowV1alpha1LogEntry;
