/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1DataSource = require('./IoArgoprojWorkflowV1alpha1DataSource');
const IoArgoprojWorkflowV1alpha1TransformationStep = require('./IoArgoprojWorkflowV1alpha1TransformationStep');

/**
 * The IoArgoprojWorkflowV1alpha1Data model module.
 * @module model/IoArgoprojWorkflowV1alpha1Data
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1Data {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1Data</code>.
   * Data is a data template
   * @alias module:model/IoArgoprojWorkflowV1alpha1Data
   * @class
   * @param source {module:model/IoArgoprojWorkflowV1alpha1DataSource} 
   * @param transformation {Array.<module:model/IoArgoprojWorkflowV1alpha1TransformationStep>} Transformation applies a set of transformations
   */
  constructor(source, transformation) {
    this.source = source;
    this.transformation = transformation;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1Data} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1Data} The populated <code>IoArgoprojWorkflowV1alpha1Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1Data();
      if (data.hasOwnProperty('source'))
        obj.source = IoArgoprojWorkflowV1alpha1DataSource.constructFromObject(data['source']);
      if (data.hasOwnProperty('transformation'))
        obj.transformation = ApiClient.convertToType(data['transformation'], [IoArgoprojWorkflowV1alpha1TransformationStep]);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1DataSource} source
 */
IoArgoprojWorkflowV1alpha1Data.prototype.source = undefined;

/**
 * Transformation applies a set of transformations
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1TransformationStep>} transformation
 */
IoArgoprojWorkflowV1alpha1Data.prototype.transformation = undefined;

module.exports = IoArgoprojWorkflowV1alpha1Data;
