/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1ArtGCStatus model module.
 * @module model/IoArgoprojWorkflowV1alpha1ArtGCStatus
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1ArtGCStatus {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1ArtGCStatus</code>.
   * ArtGCStatus maintains state related to ArtifactGC
   * @alias module:model/IoArgoprojWorkflowV1alpha1ArtGCStatus
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1ArtGCStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1ArtGCStatus} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1ArtGCStatus} The populated <code>IoArgoprojWorkflowV1alpha1ArtGCStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1ArtGCStatus();
      if (data.hasOwnProperty('notSpecified'))
        obj.notSpecified = ApiClient.convertToType(data['notSpecified'], 'Boolean');
      if (data.hasOwnProperty('podsRecouped'))
        obj.podsRecouped = ApiClient.convertToType(data['podsRecouped'], {'String': 'Boolean'});
      if (data.hasOwnProperty('strategiesProcessed'))
        obj.strategiesProcessed = ApiClient.convertToType(data['strategiesProcessed'], {'String': 'Boolean'});
    }
    return obj;
  }
}

/**
 * if this is true, we already checked to see if we need to do it and we don't
 * @member {Boolean} notSpecified
 */
IoArgoprojWorkflowV1alpha1ArtGCStatus.prototype.notSpecified = undefined;

/**
 * have completed Pods been processed? (mapped by Pod name) used to prevent re-processing the Status of a Pod more than once
 * @member {Object.<String, Boolean>} podsRecouped
 */
IoArgoprojWorkflowV1alpha1ArtGCStatus.prototype.podsRecouped = undefined;

/**
 * have Pods been started to perform this strategy? (enables us not to re-process what we've already done)
 * @member {Object.<String, Boolean>} strategiesProcessed
 */
IoArgoprojWorkflowV1alpha1ArtGCStatus.prototype.strategiesProcessed = undefined;

module.exports = IoArgoprojWorkflowV1alpha1ArtGCStatus;
