/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApimachineryPkgApisMetaV1LabelSelector = require('./IoK8sApimachineryPkgApisMetaV1LabelSelector');

/**
 * The IoArgoprojWorkflowV1alpha1PodGC model module.
 * @module model/IoArgoprojWorkflowV1alpha1PodGC
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1PodGC {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1PodGC</code>.
   * PodGC describes how to delete completed pods as they complete
   * @alias module:model/IoArgoprojWorkflowV1alpha1PodGC
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1PodGC</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1PodGC} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1PodGC} The populated <code>IoArgoprojWorkflowV1alpha1PodGC</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1PodGC();
      if (data.hasOwnProperty('deleteDelayDuration'))
        obj.deleteDelayDuration = ApiClient.convertToType(data['deleteDelayDuration'], 'String');
      if (data.hasOwnProperty('labelSelector'))
        obj.labelSelector = IoK8sApimachineryPkgApisMetaV1LabelSelector.constructFromObject(data['labelSelector']);
      if (data.hasOwnProperty('strategy'))
        obj.strategy = ApiClient.convertToType(data['strategy'], 'String');
    }
    return obj;
  }
}

/**
 * DeleteDelayDuration specifies the duration before pods in the GC queue get deleted.
 * @member {String} deleteDelayDuration
 */
IoArgoprojWorkflowV1alpha1PodGC.prototype.deleteDelayDuration = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1LabelSelector} labelSelector
 */
IoArgoprojWorkflowV1alpha1PodGC.prototype.labelSelector = undefined;

/**
 * Strategy is the strategy to use. One of \"OnPodCompletion\", \"OnPodSuccess\", \"OnWorkflowCompletion\", \"OnWorkflowSuccess\". If unset, does not delete Pods
 * @member {String} strategy
 */
IoArgoprojWorkflowV1alpha1PodGC.prototype.strategy = undefined;

module.exports = IoArgoprojWorkflowV1alpha1PodGC;
