/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest model module.
 * @module model/IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest} The populated <code>IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
      if (data.hasOwnProperty('nodeFieldSelector'))
        obj.nodeFieldSelector = ApiClient.convertToType(data['nodeFieldSelector'], 'String');
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], ['String']);
      if (data.hasOwnProperty('restartSuccessful'))
        obj.restartSuccessful = ApiClient.convertToType(data['restartSuccessful'], 'Boolean');
      if (data.hasOwnProperty('uid'))
        obj.uid = ApiClient.convertToType(data['uid'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest.prototype.name = undefined;

/**
 * @member {String} namespace
 */
IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest.prototype.namespace = undefined;

/**
 * @member {String} nodeFieldSelector
 */
IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest.prototype.nodeFieldSelector = undefined;

/**
 * @member {Array.<String>} parameters
 */
IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest.prototype.parameters = undefined;

/**
 * @member {Boolean} restartSuccessful
 */
IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest.prototype.restartSuccessful = undefined;

/**
 * @member {String} uid
 */
IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest.prototype.uid = undefined;

module.exports = IoArgoprojWorkflowV1alpha1RetryArchivedWorkflowRequest;
