/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1CatchupConfiguration model module.
 * @module model/IoArgoprojEventsV1alpha1CatchupConfiguration
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1CatchupConfiguration {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1CatchupConfiguration</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1CatchupConfiguration
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1CatchupConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1CatchupConfiguration} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1CatchupConfiguration} The populated <code>IoArgoprojEventsV1alpha1CatchupConfiguration</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1CatchupConfiguration();
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('maxDuration'))
        obj.maxDuration = ApiClient.convertToType(data['maxDuration'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} enabled
 */
IoArgoprojEventsV1alpha1CatchupConfiguration.prototype.enabled = undefined;

/**
 * @member {String} maxDuration
 */
IoArgoprojEventsV1alpha1CatchupConfiguration.prototype.maxDuration = undefined;

module.exports = IoArgoprojEventsV1alpha1CatchupConfiguration;
