/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1RateLimit model module.
 * @module model/IoArgoprojEventsV1alpha1RateLimit
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1RateLimit {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1RateLimit</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1RateLimit
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1RateLimit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1RateLimit} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1RateLimit} The populated <code>IoArgoprojEventsV1alpha1RateLimit</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1RateLimit();
      if (data.hasOwnProperty('requestsPerUnit'))
        obj.requestsPerUnit = ApiClient.convertToType(data['requestsPerUnit'], 'Number');
      if (data.hasOwnProperty('unit'))
        obj.unit = ApiClient.convertToType(data['unit'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} requestsPerUnit
 */
IoArgoprojEventsV1alpha1RateLimit.prototype.requestsPerUnit = undefined;

/**
 * @member {String} unit
 */
IoArgoprojEventsV1alpha1RateLimit.prototype.unit = undefined;

module.exports = IoArgoprojEventsV1alpha1RateLimit;
