/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1Artifact = require('./IoArgoprojWorkflowV1alpha1Artifact');

/**
 * The IoArgoprojWorkflowV1alpha1ManifestFrom model module.
 * @module model/IoArgoprojWorkflowV1alpha1ManifestFrom
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1ManifestFrom {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1ManifestFrom</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1ManifestFrom
   * @class
   * @param artifact {module:model/IoArgoprojWorkflowV1alpha1Artifact} 
   */
  constructor(artifact) {
    this.artifact = artifact;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1ManifestFrom</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1ManifestFrom} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1ManifestFrom} The populated <code>IoArgoprojWorkflowV1alpha1ManifestFrom</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1ManifestFrom();
      if (data.hasOwnProperty('artifact'))
        obj.artifact = IoArgoprojWorkflowV1alpha1Artifact.constructFromObject(data['artifact']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1Artifact} artifact
 */
IoArgoprojWorkflowV1alpha1ManifestFrom.prototype.artifact = undefined;

module.exports = IoArgoprojWorkflowV1alpha1ManifestFrom;
