/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1Gauge model module.
 * @module model/IoArgoprojWorkflowV1alpha1Gauge
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1Gauge {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1Gauge</code>.
   * Gauge is a Gauge prometheus metric
   * @alias module:model/IoArgoprojWorkflowV1alpha1Gauge
   * @class
   * @param realtime {Boolean} Realtime emits this metric in real time if applicable
   * @param value {String} Value is the value to be used in the operation with the metric's current value. If no operation is set, value is the value of the metric
   */
  constructor(realtime, value) {
    this.realtime = realtime;
    this.value = value;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1Gauge</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1Gauge} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1Gauge} The populated <code>IoArgoprojWorkflowV1alpha1Gauge</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1Gauge();
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('realtime'))
        obj.realtime = ApiClient.convertToType(data['realtime'], 'Boolean');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * Operation defines the operation to apply with value and the metrics' current value
 * @member {String} operation
 */
IoArgoprojWorkflowV1alpha1Gauge.prototype.operation = undefined;

/**
 * Realtime emits this metric in real time if applicable
 * @member {Boolean} realtime
 */
IoArgoprojWorkflowV1alpha1Gauge.prototype.realtime = undefined;

/**
 * Value is the value to be used in the operation with the metric's current value. If no operation is set, value is the value of the metric
 * @member {String} value
 */
IoArgoprojWorkflowV1alpha1Gauge.prototype.value = undefined;

module.exports = IoArgoprojWorkflowV1alpha1Gauge;
