/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1GithubAppCreds model module.
 * @module model/IoArgoprojEventsV1alpha1GithubAppCreds
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1GithubAppCreds {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1GithubAppCreds</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1GithubAppCreds
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1GithubAppCreds</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1GithubAppCreds} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1GithubAppCreds} The populated <code>IoArgoprojEventsV1alpha1GithubAppCreds</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1GithubAppCreds();
      if (data.hasOwnProperty('appID'))
        obj.appID = ApiClient.convertToType(data['appID'], 'String');
      if (data.hasOwnProperty('installationID'))
        obj.installationID = ApiClient.convertToType(data['installationID'], 'String');
      if (data.hasOwnProperty('privateKey'))
        obj.privateKey = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['privateKey']);
    }
    return obj;
  }
}

/**
 * @member {String} appID
 */
IoArgoprojEventsV1alpha1GithubAppCreds.prototype.appID = undefined;

/**
 * @member {String} installationID
 */
IoArgoprojEventsV1alpha1GithubAppCreds.prototype.installationID = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} privateKey
 */
IoArgoprojEventsV1alpha1GithubAppCreds.prototype.privateKey = undefined;

module.exports = IoArgoprojEventsV1alpha1GithubAppCreds;
