/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApimachineryPkgUtilIntstrIntOrString = require('./IoK8sApimachineryPkgUtilIntstrIntOrString');

/**
 * The IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy model module.
 * @module model/IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy</code>.
   * ContainerSetRetryStrategy provides controls on how to retry a container set
   * @alias module:model/IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy
   * @class
   * @param retries {module:model/IoK8sApimachineryPkgUtilIntstrIntOrString} 
   */
  constructor(retries) {
    this.retries = retries;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy} The populated <code>IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy();
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'String');
      if (data.hasOwnProperty('retries'))
        obj.retries = IoK8sApimachineryPkgUtilIntstrIntOrString.constructFromObject(data['retries']);
    }
    return obj;
  }
}

/**
 * Duration is the time between each retry, examples values are \"300ms\", \"1s\" or \"5m\". Valid time units are \"ns\", \"us\" (or \"µs\"), \"ms\", \"s\", \"m\", \"h\".
 * @member {String} duration
 */
IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.prototype.duration = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgUtilIntstrIntOrString} retries
 */
IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.prototype.retries = undefined;

module.exports = IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy;
