/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1EventSourceFilter = require('./IoArgoprojEventsV1alpha1EventSourceFilter');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1AzureQueueStorageEventSource model module.
 * @module model/IoArgoprojEventsV1alpha1AzureQueueStorageEventSource
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1AzureQueueStorageEventSource {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1AzureQueueStorageEventSource</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1AzureQueueStorageEventSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1AzureQueueStorageEventSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1AzureQueueStorageEventSource} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1AzureQueueStorageEventSource} The populated <code>IoArgoprojEventsV1alpha1AzureQueueStorageEventSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1AzureQueueStorageEventSource();
      if (data.hasOwnProperty('connectionString'))
        obj.connectionString = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['connectionString']);
      if (data.hasOwnProperty('decodeMessage'))
        obj.decodeMessage = ApiClient.convertToType(data['decodeMessage'], 'Boolean');
      if (data.hasOwnProperty('dlq'))
        obj.dlq = ApiClient.convertToType(data['dlq'], 'Boolean');
      if (data.hasOwnProperty('filter'))
        obj.filter = IoArgoprojEventsV1alpha1EventSourceFilter.constructFromObject(data['filter']);
      if (data.hasOwnProperty('jsonBody'))
        obj.jsonBody = ApiClient.convertToType(data['jsonBody'], 'Boolean');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], {'String': 'String'});
      if (data.hasOwnProperty('queueName'))
        obj.queueName = ApiClient.convertToType(data['queueName'], 'String');
      if (data.hasOwnProperty('storageAccountName'))
        obj.storageAccountName = ApiClient.convertToType(data['storageAccountName'], 'String');
      if (data.hasOwnProperty('waitTimeInSeconds'))
        obj.waitTimeInSeconds = ApiClient.convertToType(data['waitTimeInSeconds'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} connectionString
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.connectionString = undefined;

/**
 * @member {Boolean} decodeMessage
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.decodeMessage = undefined;

/**
 * @member {Boolean} dlq
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.dlq = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1EventSourceFilter} filter
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.filter = undefined;

/**
 * @member {Boolean} jsonBody
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.jsonBody = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.metadata = undefined;

/**
 * @member {String} queueName
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.queueName = undefined;

/**
 * @member {String} storageAccountName
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.storageAccountName = undefined;

/**
 * @member {Number} waitTimeInSeconds
 */
IoArgoprojEventsV1alpha1AzureQueueStorageEventSource.prototype.waitTimeInSeconds = undefined;

module.exports = IoArgoprojEventsV1alpha1AzureQueueStorageEventSource;
