/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1Selector model module.
 * @module model/IoArgoprojEventsV1alpha1Selector
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1Selector {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1Selector</code>.
   * Selector represents conditional operation to select K8s objects.
   * @alias module:model/IoArgoprojEventsV1alpha1Selector
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1Selector</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1Selector} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1Selector} The populated <code>IoArgoprojEventsV1alpha1Selector</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1Selector();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} key
 */
IoArgoprojEventsV1alpha1Selector.prototype.key = undefined;

/**
 * @member {String} operation
 */
IoArgoprojEventsV1alpha1Selector.prototype.operation = undefined;

/**
 * @member {String} value
 */
IoArgoprojEventsV1alpha1Selector.prototype.value = undefined;

module.exports = IoArgoprojEventsV1alpha1Selector;
