/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1WorkflowTemplateRef model module.
 * @module model/IoArgoprojWorkflowV1alpha1WorkflowTemplateRef
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1WorkflowTemplateRef {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1WorkflowTemplateRef</code>.
   * WorkflowTemplateRef is a reference to a WorkflowTemplate resource.
   * @alias module:model/IoArgoprojWorkflowV1alpha1WorkflowTemplateRef
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1WorkflowTemplateRef</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1WorkflowTemplateRef} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1WorkflowTemplateRef} The populated <code>IoArgoprojWorkflowV1alpha1WorkflowTemplateRef</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1WorkflowTemplateRef();
      if (data.hasOwnProperty('clusterScope'))
        obj.clusterScope = ApiClient.convertToType(data['clusterScope'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * ClusterScope indicates the referred template is cluster scoped (i.e. a ClusterWorkflowTemplate).
 * @member {Boolean} clusterScope
 */
IoArgoprojWorkflowV1alpha1WorkflowTemplateRef.prototype.clusterScope = undefined;

/**
 * Name is the resource name of the workflow template.
 * @member {String} name
 */
IoArgoprojWorkflowV1alpha1WorkflowTemplateRef.prototype.name = undefined;

module.exports = IoArgoprojWorkflowV1alpha1WorkflowTemplateRef;
