/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1Int64OrString model module.
 * @module model/IoArgoprojEventsV1alpha1Int64OrString
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1Int64OrString {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1Int64OrString</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1Int64OrString
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1Int64OrString</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1Int64OrString} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1Int64OrString} The populated <code>IoArgoprojEventsV1alpha1Int64OrString</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1Int64OrString();
      if (data.hasOwnProperty('int64Val'))
        obj.int64Val = ApiClient.convertToType(data['int64Val'], 'String');
      if (data.hasOwnProperty('strVal'))
        obj.strVal = ApiClient.convertToType(data['strVal'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} int64Val
 */
module.exports.int64Val = undefined;

/**
 * @member {String} strVal
 */
module.exports.strVal = undefined;

/**
 * @member {String} type
 */
module.exports.type = undefined;

module.exports = IoArgoprojEventsV1alpha1Int64OrString;
