/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1Metadata model module.
 * @module model/IoArgoprojWorkflowV1alpha1Metadata
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1Metadata {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1Metadata</code>.
   * Pod metdata
   * @alias module:model/IoArgoprojWorkflowV1alpha1Metadata
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1Metadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1Metadata} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1Metadata} The populated <code>IoArgoprojWorkflowV1alpha1Metadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1Metadata();
      if (data.hasOwnProperty('annotations'))
        obj.annotations = ApiClient.convertToType(data['annotations'], {'String': 'String'});
      if (data.hasOwnProperty('labels'))
        obj.labels = ApiClient.convertToType(data['labels'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * @member {Object.<String, String>} annotations
 */
IoArgoprojWorkflowV1alpha1Metadata.prototype.annotations = undefined;

/**
 * @member {Object.<String, String>} labels
 */
IoArgoprojWorkflowV1alpha1Metadata.prototype.labels = undefined;

module.exports = IoArgoprojWorkflowV1alpha1Metadata;
