/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1Column = require('./IoArgoprojWorkflowV1alpha1Column');
const IoArgoprojWorkflowV1alpha1Link = require('./IoArgoprojWorkflowV1alpha1Link');

/**
 * The IoArgoprojWorkflowV1alpha1InfoResponse model module.
 * @module model/IoArgoprojWorkflowV1alpha1InfoResponse
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1InfoResponse {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1InfoResponse</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1InfoResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1InfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1InfoResponse} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1InfoResponse} The populated <code>IoArgoprojWorkflowV1alpha1InfoResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1InfoResponse();
      if (data.hasOwnProperty('columns'))
        obj.columns = ApiClient.convertToType(data['columns'], [IoArgoprojWorkflowV1alpha1Column]);
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], [IoArgoprojWorkflowV1alpha1Link]);
      if (data.hasOwnProperty('managedNamespace'))
        obj.managedNamespace = ApiClient.convertToType(data['managedNamespace'], 'String');
      if (data.hasOwnProperty('modals'))
        obj.modals = ApiClient.convertToType(data['modals'], {'String': 'Boolean'});
      if (data.hasOwnProperty('navColor'))
        obj.navColor = ApiClient.convertToType(data['navColor'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1Column>} columns
 */
IoArgoprojWorkflowV1alpha1InfoResponse.prototype.columns = undefined;

/**
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1Link>} links
 */
IoArgoprojWorkflowV1alpha1InfoResponse.prototype.links = undefined;

/**
 * @member {String} managedNamespace
 */
IoArgoprojWorkflowV1alpha1InfoResponse.prototype.managedNamespace = undefined;

/**
 * @member {Object.<String, Boolean>} modals
 */
IoArgoprojWorkflowV1alpha1InfoResponse.prototype.modals = undefined;

/**
 * @member {String} navColor
 */
IoArgoprojWorkflowV1alpha1InfoResponse.prototype.navColor = undefined;

module.exports = IoArgoprojWorkflowV1alpha1InfoResponse;
