/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1EventSourceFilter = require('./IoArgoprojEventsV1alpha1EventSourceFilter');
const IoArgoprojEventsV1alpha1TLSConfig = require('./IoArgoprojEventsV1alpha1TLSConfig');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1AzureServiceBusEventSource model module.
 * @module model/IoArgoprojEventsV1alpha1AzureServiceBusEventSource
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1AzureServiceBusEventSource {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1AzureServiceBusEventSource</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1AzureServiceBusEventSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1AzureServiceBusEventSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1AzureServiceBusEventSource} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1AzureServiceBusEventSource} The populated <code>IoArgoprojEventsV1alpha1AzureServiceBusEventSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1AzureServiceBusEventSource();
      if (data.hasOwnProperty('connectionString'))
        obj.connectionString = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['connectionString']);
      if (data.hasOwnProperty('filter'))
        obj.filter = IoArgoprojEventsV1alpha1EventSourceFilter.constructFromObject(data['filter']);
      if (data.hasOwnProperty('fullyQualifiedNamespace'))
        obj.fullyQualifiedNamespace = ApiClient.convertToType(data['fullyQualifiedNamespace'], 'String');
      if (data.hasOwnProperty('jsonBody'))
        obj.jsonBody = ApiClient.convertToType(data['jsonBody'], 'Boolean');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], {'String': 'String'});
      if (data.hasOwnProperty('queueName'))
        obj.queueName = ApiClient.convertToType(data['queueName'], 'String');
      if (data.hasOwnProperty('subscriptionName'))
        obj.subscriptionName = ApiClient.convertToType(data['subscriptionName'], 'String');
      if (data.hasOwnProperty('tls'))
        obj.tls = IoArgoprojEventsV1alpha1TLSConfig.constructFromObject(data['tls']);
      if (data.hasOwnProperty('topicName'))
        obj.topicName = ApiClient.convertToType(data['topicName'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} connectionString
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.connectionString = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1EventSourceFilter} filter
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.filter = undefined;

/**
 * @member {String} fullyQualifiedNamespace
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.fullyQualifiedNamespace = undefined;

/**
 * @member {Boolean} jsonBody
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.jsonBody = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.metadata = undefined;

/**
 * @member {String} queueName
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.queueName = undefined;

/**
 * @member {String} subscriptionName
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.subscriptionName = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1TLSConfig} tls
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.tls = undefined;

/**
 * @member {String} topicName
 */
IoArgoprojEventsV1alpha1AzureServiceBusEventSource.prototype.topicName = undefined;

module.exports = IoArgoprojEventsV1alpha1AzureServiceBusEventSource;
