/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1Amount = require('./IoArgoprojWorkflowV1alpha1Amount');

/**
 * The IoArgoprojWorkflowV1alpha1Histogram model module.
 * @module model/IoArgoprojWorkflowV1alpha1Histogram
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1Histogram {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1Histogram</code>.
   * Histogram is a Histogram prometheus metric
   * @alias module:model/IoArgoprojWorkflowV1alpha1Histogram
   * @class
   * @param buckets {Array.<module:model/IoArgoprojWorkflowV1alpha1Amount>} Buckets is a list of bucket divisors for the histogram
   * @param value {String} Value is the value of the metric
   */
  constructor(buckets, value) {
    this.buckets = buckets;
    this.value = value;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1Histogram</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1Histogram} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1Histogram} The populated <code>IoArgoprojWorkflowV1alpha1Histogram</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1Histogram();
      if (data.hasOwnProperty('buckets'))
        obj.buckets = ApiClient.convertToType(data['buckets'], [IoArgoprojWorkflowV1alpha1Amount]);
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * Buckets is a list of bucket divisors for the histogram
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1Amount>} buckets
 */
IoArgoprojWorkflowV1alpha1Histogram.prototype.buckets = undefined;

/**
 * Value is the value of the metric
 * @member {String} value
 */
IoArgoprojWorkflowV1alpha1Histogram.prototype.value = undefined;

module.exports = IoArgoprojWorkflowV1alpha1Histogram;
