/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1SubmitOpts = require('./IoArgoprojWorkflowV1alpha1SubmitOpts');

/**
 * The IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest model module.
 * @module model/IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest} The populated <code>IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest();
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
      if (data.hasOwnProperty('resourceKind'))
        obj.resourceKind = ApiClient.convertToType(data['resourceKind'], 'String');
      if (data.hasOwnProperty('resourceName'))
        obj.resourceName = ApiClient.convertToType(data['resourceName'], 'String');
      if (data.hasOwnProperty('submitOptions'))
        obj.submitOptions = IoArgoprojWorkflowV1alpha1SubmitOpts.constructFromObject(data['submitOptions']);
    }
    return obj;
  }
}

/**
 * @member {String} namespace
 */
IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest.prototype.namespace = undefined;

/**
 * @member {String} resourceKind
 */
IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest.prototype.resourceKind = undefined;

/**
 * @member {String} resourceName
 */
IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest.prototype.resourceName = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1SubmitOpts} submitOptions
 */
IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest.prototype.submitOptions = undefined;

module.exports = IoArgoprojWorkflowV1alpha1WorkflowSubmitRequest;
