/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1GitRemoteConfig model module.
 * @module model/IoArgoprojEventsV1alpha1GitRemoteConfig
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1GitRemoteConfig {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1GitRemoteConfig</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1GitRemoteConfig
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1GitRemoteConfig</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1GitRemoteConfig} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1GitRemoteConfig} The populated <code>IoArgoprojEventsV1alpha1GitRemoteConfig</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1GitRemoteConfig();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('urls'))
        obj.urls = ApiClient.convertToType(data['urls'], ['String']);
    }
    return obj;
  }
}

/**
 * Name of the remote to fetch from.
 * @member {String} name
 */
module.exports.name = undefined;

/**
 * URLs the URLs of a remote repository. It must be non-empty. Fetch will always use the first URL, while push will use all of them.
 * @member {Array.<String>} urls
 */
module.exports.urls = undefined;

module.exports = IoArgoprojEventsV1alpha1GitRemoteConfig;
