/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1StatusPolicy model module.
 * @module model/IoArgoprojEventsV1alpha1StatusPolicy
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1StatusPolicy {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1StatusPolicy</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1StatusPolicy
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1StatusPolicy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1StatusPolicy} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1StatusPolicy} The populated <code>IoArgoprojEventsV1alpha1StatusPolicy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1StatusPolicy();
      if (data.hasOwnProperty('allow'))
        obj.allow = ApiClient.convertToType(data['allow'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Array.<Number>} allow
 */
IoArgoprojEventsV1alpha1StatusPolicy.prototype.allow = undefined;

module.exports = IoArgoprojEventsV1alpha1StatusPolicy;
