/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1LabelValueFrom model module.
 * @module model/IoArgoprojWorkflowV1alpha1LabelValueFrom
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1LabelValueFrom {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1LabelValueFrom</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1LabelValueFrom
   * @class
   * @param expression {String} 
   */
  constructor(expression) {
    this.expression = expression;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1LabelValueFrom</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1LabelValueFrom} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1LabelValueFrom} The populated <code>IoArgoprojWorkflowV1alpha1LabelValueFrom</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1LabelValueFrom();
      if (data.hasOwnProperty('expression'))
        obj.expression = ApiClient.convertToType(data['expression'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} expression
 */
IoArgoprojWorkflowV1alpha1LabelValueFrom.prototype.expression = undefined;

module.exports = IoArgoprojWorkflowV1alpha1LabelValueFrom;
