/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1Condition model module.
 * @module model/IoArgoprojWorkflowV1alpha1Condition
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1Condition {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1Condition</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1Condition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1Condition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1Condition} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1Condition} The populated <code>IoArgoprojWorkflowV1alpha1Condition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1Condition();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * Message is the condition message
 * @member {String} message
 */
IoArgoprojWorkflowV1alpha1Condition.prototype.message = undefined;

/**
 * Status is the status of the condition
 * @member {String} status
 */
IoArgoprojWorkflowV1alpha1Condition.prototype.status = undefined;

/**
 * Type is the type of condition
 * @member {String} type
 */
IoArgoprojWorkflowV1alpha1Condition.prototype.type = undefined;

module.exports = IoArgoprojWorkflowV1alpha1Condition;
