/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojEventsV1alpha1URLArtifact model module.
 * @module model/IoArgoprojEventsV1alpha1URLArtifact
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1URLArtifact {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1URLArtifact</code>.
   * URLArtifact contains information about an artifact at an http endpoint.
   * @alias module:model/IoArgoprojEventsV1alpha1URLArtifact
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1URLArtifact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1URLArtifact} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1URLArtifact} The populated <code>IoArgoprojEventsV1alpha1URLArtifact</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1URLArtifact();
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('verifyCert'))
        obj.verifyCert = ApiClient.convertToType(data['verifyCert'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} path
 */
IoArgoprojEventsV1alpha1URLArtifact.prototype.path = undefined;

/**
 * @member {Boolean} verifyCert
 */
IoArgoprojEventsV1alpha1URLArtifact.prototype.verifyCert = undefined;

module.exports = IoArgoprojEventsV1alpha1URLArtifact;
