/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1SensorSpec = require('./IoArgoprojEventsV1alpha1SensorSpec');
const IoArgoprojEventsV1alpha1SensorStatus = require('./IoArgoprojEventsV1alpha1SensorStatus');
const IoK8sApimachineryPkgApisMetaV1ObjectMeta = require('./IoK8sApimachineryPkgApisMetaV1ObjectMeta');

/**
 * The IoArgoprojEventsV1alpha1Sensor model module.
 * @module model/IoArgoprojEventsV1alpha1Sensor
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1Sensor {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1Sensor</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1Sensor
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1Sensor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1Sensor} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1Sensor} The populated <code>IoArgoprojEventsV1alpha1Sensor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1Sensor();
      if (data.hasOwnProperty('metadata'))
        obj.metadata = IoK8sApimachineryPkgApisMetaV1ObjectMeta.constructFromObject(data['metadata']);
      if (data.hasOwnProperty('spec'))
        obj.spec = IoArgoprojEventsV1alpha1SensorSpec.constructFromObject(data['spec']);
      if (data.hasOwnProperty('status'))
        obj.status = IoArgoprojEventsV1alpha1SensorStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1ObjectMeta} metadata
 */
IoArgoprojEventsV1alpha1Sensor.prototype.metadata = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1SensorSpec} spec
 */
IoArgoprojEventsV1alpha1Sensor.prototype.spec = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1SensorStatus} status
 */
IoArgoprojEventsV1alpha1Sensor.prototype.status = undefined;

module.exports = IoArgoprojEventsV1alpha1Sensor;
