/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1WebhookContext = require('./IoArgoprojEventsV1alpha1WebhookContext');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1StripeEventSource model module.
 * @module model/IoArgoprojEventsV1alpha1StripeEventSource
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1StripeEventSource {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1StripeEventSource</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1StripeEventSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1StripeEventSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1StripeEventSource} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1StripeEventSource} The populated <code>IoArgoprojEventsV1alpha1StripeEventSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1StripeEventSource();
      if (data.hasOwnProperty('apiKey'))
        obj.apiKey = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['apiKey']);
      if (data.hasOwnProperty('createWebhook'))
        obj.createWebhook = ApiClient.convertToType(data['createWebhook'], 'Boolean');
      if (data.hasOwnProperty('eventFilter'))
        obj.eventFilter = ApiClient.convertToType(data['eventFilter'], ['String']);
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], {'String': 'String'});
      if (data.hasOwnProperty('webhook'))
        obj.webhook = IoArgoprojEventsV1alpha1WebhookContext.constructFromObject(data['webhook']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} apiKey
 */
IoArgoprojEventsV1alpha1StripeEventSource.prototype.apiKey = undefined;

/**
 * @member {Boolean} createWebhook
 */
IoArgoprojEventsV1alpha1StripeEventSource.prototype.createWebhook = undefined;

/**
 * @member {Array.<String>} eventFilter
 */
IoArgoprojEventsV1alpha1StripeEventSource.prototype.eventFilter = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
IoArgoprojEventsV1alpha1StripeEventSource.prototype.metadata = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1WebhookContext} webhook
 */
IoArgoprojEventsV1alpha1StripeEventSource.prototype.webhook = undefined;

module.exports = IoArgoprojEventsV1alpha1StripeEventSource;
