/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1Event model module.
 * @module model/IoArgoprojWorkflowV1alpha1Event
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1Event {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1Event</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1Event
   * @class
   * @param selector {String} Selector (https://github.com/expr-lang/expr) that we must must match the io.argoproj.workflow.v1alpha1. E.g. `payload.message == \"test\"`
   */
  constructor(selector) {
    this.selector = selector;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1Event</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1Event} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1Event} The populated <code>IoArgoprojWorkflowV1alpha1Event</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1Event();
      if (data.hasOwnProperty('selector'))
        obj.selector = ApiClient.convertToType(data['selector'], 'String');
    }
    return obj;
  }
}

/**
 * Selector (https://github.com/expr-lang/expr) that we must must match the io.argoproj.workflow.v1alpha1. E.g. `payload.message == \"test\"`
 * @member {String} selector
 */
IoArgoprojWorkflowV1alpha1Event.prototype.selector = undefined;

module.exports = IoArgoprojWorkflowV1alpha1Event;
