/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1Selector = require('./IoArgoprojEventsV1alpha1Selector');
const IoK8sApimachineryPkgApisMetaV1Time = require('./IoK8sApimachineryPkgApisMetaV1Time');

/**
 * The IoArgoprojEventsV1alpha1ResourceFilter model module.
 * @module model/IoArgoprojEventsV1alpha1ResourceFilter
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1ResourceFilter {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1ResourceFilter</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1ResourceFilter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1ResourceFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1ResourceFilter} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1ResourceFilter} The populated <code>IoArgoprojEventsV1alpha1ResourceFilter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1ResourceFilter();
      if (data.hasOwnProperty('afterStart'))
        obj.afterStart = ApiClient.convertToType(data['afterStart'], 'Boolean');
      if (data.hasOwnProperty('createdBy'))
        obj.createdBy = IoK8sApimachineryPkgApisMetaV1Time.constructFromObject(data['createdBy']);
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], [IoArgoprojEventsV1alpha1Selector]);
      if (data.hasOwnProperty('labels'))
        obj.labels = ApiClient.convertToType(data['labels'], [IoArgoprojEventsV1alpha1Selector]);
      if (data.hasOwnProperty('prefix'))
        obj.prefix = ApiClient.convertToType(data['prefix'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} afterStart
 */
IoArgoprojEventsV1alpha1ResourceFilter.prototype.afterStart = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1Time} createdBy
 */
IoArgoprojEventsV1alpha1ResourceFilter.prototype.createdBy = undefined;

/**
 * @member {Array.<module:model/IoArgoprojEventsV1alpha1Selector>} fields
 */
IoArgoprojEventsV1alpha1ResourceFilter.prototype.fields = undefined;

/**
 * @member {Array.<module:model/IoArgoprojEventsV1alpha1Selector>} labels
 */
IoArgoprojEventsV1alpha1ResourceFilter.prototype.labels = undefined;

/**
 * @member {String} prefix
 */
IoArgoprojEventsV1alpha1ResourceFilter.prototype.prefix = undefined;

module.exports = IoArgoprojEventsV1alpha1ResourceFilter;
