/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1WorkflowEventBinding = require('./IoArgoprojWorkflowV1alpha1WorkflowEventBinding');
const IoK8sApimachineryPkgApisMetaV1ListMeta = require('./IoK8sApimachineryPkgApisMetaV1ListMeta');

/**
 * The IoArgoprojWorkflowV1alpha1WorkflowEventBindingList model module.
 * @module model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingList
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1WorkflowEventBindingList {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1WorkflowEventBindingList</code>.
   * WorkflowEventBindingList is list of event resources
   * @alias module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingList
   * @class
   * @param items {Array.<module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBinding>} 
   * @param metadata {module:model/IoK8sApimachineryPkgApisMetaV1ListMeta} 
   */
  constructor(items, metadata) {
    this.items = items;
    this.metadata = metadata;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1WorkflowEventBindingList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingList} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBindingList} The populated <code>IoArgoprojWorkflowV1alpha1WorkflowEventBindingList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1WorkflowEventBindingList();
      if (data.hasOwnProperty('apiVersion'))
        obj.apiVersion = ApiClient.convertToType(data['apiVersion'], 'String');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [IoArgoprojWorkflowV1alpha1WorkflowEventBinding]);
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], 'String');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = IoK8sApimachineryPkgApisMetaV1ListMeta.constructFromObject(data['metadata']);
    }
    return obj;
  }
}

/**
 * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#resources
 * @member {String} apiVersion
 */
IoArgoprojWorkflowV1alpha1WorkflowEventBindingList.prototype.apiVersion = undefined;

/**
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1WorkflowEventBinding>} items
 */
IoArgoprojWorkflowV1alpha1WorkflowEventBindingList.prototype.items = undefined;

/**
 * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.io.k8s.community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
 * @member {String} kind
 */
IoArgoprojWorkflowV1alpha1WorkflowEventBindingList.prototype.kind = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1ListMeta} metadata
 */
IoArgoprojWorkflowV1alpha1WorkflowEventBindingList.prototype.metadata = undefined;

module.exports = IoArgoprojWorkflowV1alpha1WorkflowEventBindingList;
