/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository = require('./IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository');
const IoArgoprojWorkflowV1alpha1AzureArtifactRepository = require('./IoArgoprojWorkflowV1alpha1AzureArtifactRepository');
const IoArgoprojWorkflowV1alpha1GCSArtifactRepository = require('./IoArgoprojWorkflowV1alpha1GCSArtifactRepository');
const IoArgoprojWorkflowV1alpha1HDFSArtifactRepository = require('./IoArgoprojWorkflowV1alpha1HDFSArtifactRepository');
const IoArgoprojWorkflowV1alpha1OSSArtifactRepository = require('./IoArgoprojWorkflowV1alpha1OSSArtifactRepository');
const IoArgoprojWorkflowV1alpha1S3ArtifactRepository = require('./IoArgoprojWorkflowV1alpha1S3ArtifactRepository');

/**
 * The IoArgoprojWorkflowV1alpha1ArtifactRepository model module.
 * @module model/IoArgoprojWorkflowV1alpha1ArtifactRepository
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1ArtifactRepository {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1ArtifactRepository</code>.
   * ArtifactRepository represents an artifact repository in which a controller will store its artifacts
   * @alias module:model/IoArgoprojWorkflowV1alpha1ArtifactRepository
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1ArtifactRepository</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1ArtifactRepository} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1ArtifactRepository} The populated <code>IoArgoprojWorkflowV1alpha1ArtifactRepository</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1ArtifactRepository();
      if (data.hasOwnProperty('archiveLogs'))
        obj.archiveLogs = ApiClient.convertToType(data['archiveLogs'], 'Boolean');
      if (data.hasOwnProperty('artifactory'))
        obj.artifactory = IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository.constructFromObject(data['artifactory']);
      if (data.hasOwnProperty('azure'))
        obj.azure = IoArgoprojWorkflowV1alpha1AzureArtifactRepository.constructFromObject(data['azure']);
      if (data.hasOwnProperty('gcs'))
        obj.gcs = IoArgoprojWorkflowV1alpha1GCSArtifactRepository.constructFromObject(data['gcs']);
      if (data.hasOwnProperty('hdfs'))
        obj.hdfs = IoArgoprojWorkflowV1alpha1HDFSArtifactRepository.constructFromObject(data['hdfs']);
      if (data.hasOwnProperty('oss'))
        obj.oss = IoArgoprojWorkflowV1alpha1OSSArtifactRepository.constructFromObject(data['oss']);
      if (data.hasOwnProperty('s3'))
        obj.s3 = IoArgoprojWorkflowV1alpha1S3ArtifactRepository.constructFromObject(data['s3']);
    }
    return obj;
  }
}

/**
 * ArchiveLogs enables log archiving
 * @member {Boolean} archiveLogs
 */
IoArgoprojWorkflowV1alpha1ArtifactRepository.prototype.archiveLogs = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1ArtifactoryArtifactRepository} artifactory
 */
IoArgoprojWorkflowV1alpha1ArtifactRepository.prototype.artifactory = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1AzureArtifactRepository} azure
 */
IoArgoprojWorkflowV1alpha1ArtifactRepository.prototype.azure = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1GCSArtifactRepository} gcs
 */
IoArgoprojWorkflowV1alpha1ArtifactRepository.prototype.gcs = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1HDFSArtifactRepository} hdfs
 */
IoArgoprojWorkflowV1alpha1ArtifactRepository.prototype.hdfs = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1OSSArtifactRepository} oss
 */
IoArgoprojWorkflowV1alpha1ArtifactRepository.prototype.oss = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1S3ArtifactRepository} s3
 */
IoArgoprojWorkflowV1alpha1ArtifactRepository.prototype.s3 = undefined;

module.exports = IoArgoprojWorkflowV1alpha1ArtifactRepository;
