/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest model module.
 * @module model/IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest</code>.
   * @alias module:model/IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest} The populated <code>IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest.prototype.name = undefined;

/**
 * @member {String} namespace
 */
IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest.prototype.namespace = undefined;

module.exports = IoArgoprojWorkflowV1alpha1WorkflowSuspendRequest;
