/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1EventSourceFilter = require('./IoArgoprojEventsV1alpha1EventSourceFilter');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojEventsV1alpha1SQSEventSource model module.
 * @module model/IoArgoprojEventsV1alpha1SQSEventSource
 * @version VERSION
 */
class IoArgoprojEventsV1alpha1SQSEventSource {
  /**
   * Constructs a new <code>IoArgoprojEventsV1alpha1SQSEventSource</code>.
   * @alias module:model/IoArgoprojEventsV1alpha1SQSEventSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojEventsV1alpha1SQSEventSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojEventsV1alpha1SQSEventSource} obj Optional instance to populate.
   * @return {module:model/IoArgoprojEventsV1alpha1SQSEventSource} The populated <code>IoArgoprojEventsV1alpha1SQSEventSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojEventsV1alpha1SQSEventSource();
      if (data.hasOwnProperty('accessKey'))
        obj.accessKey = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['accessKey']);
      if (data.hasOwnProperty('dlq'))
        obj.dlq = ApiClient.convertToType(data['dlq'], 'Boolean');
      if (data.hasOwnProperty('endpoint'))
        obj.endpoint = ApiClient.convertToType(data['endpoint'], 'String');
      if (data.hasOwnProperty('filter'))
        obj.filter = IoArgoprojEventsV1alpha1EventSourceFilter.constructFromObject(data['filter']);
      if (data.hasOwnProperty('jsonBody'))
        obj.jsonBody = ApiClient.convertToType(data['jsonBody'], 'Boolean');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], {'String': 'String'});
      if (data.hasOwnProperty('queue'))
        obj.queue = ApiClient.convertToType(data['queue'], 'String');
      if (data.hasOwnProperty('queueAccountId'))
        obj.queueAccountId = ApiClient.convertToType(data['queueAccountId'], 'String');
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
      if (data.hasOwnProperty('roleARN'))
        obj.roleARN = ApiClient.convertToType(data['roleARN'], 'String');
      if (data.hasOwnProperty('secretKey'))
        obj.secretKey = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['secretKey']);
      if (data.hasOwnProperty('sessionToken'))
        obj.sessionToken = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['sessionToken']);
      if (data.hasOwnProperty('waitTimeSeconds'))
        obj.waitTimeSeconds = ApiClient.convertToType(data['waitTimeSeconds'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} accessKey
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.accessKey = undefined;

/**
 * @member {Boolean} dlq
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.dlq = undefined;

/**
 * @member {String} endpoint
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.endpoint = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1EventSourceFilter} filter
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.filter = undefined;

/**
 * @member {Boolean} jsonBody
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.jsonBody = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.metadata = undefined;

/**
 * @member {String} queue
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.queue = undefined;

/**
 * @member {String} queueAccountId
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.queueAccountId = undefined;

/**
 * @member {String} region
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.region = undefined;

/**
 * @member {String} roleARN
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.roleARN = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} secretKey
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.secretKey = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} sessionToken
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.sessionToken = undefined;

/**
 * WaitTimeSeconds is The duration (in seconds) for which the call waits for a message to arrive in the queue before returning.
 * @member {String} waitTimeSeconds
 */
IoArgoprojEventsV1alpha1SQSEventSource.prototype.waitTimeSeconds = undefined;

module.exports = IoArgoprojEventsV1alpha1SQSEventSource;
