/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojWorkflowV1alpha1MutexHolding = require('./IoArgoprojWorkflowV1alpha1MutexHolding');

/**
 * The IoArgoprojWorkflowV1alpha1MutexStatus model module.
 * @module model/IoArgoprojWorkflowV1alpha1MutexStatus
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1MutexStatus {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1MutexStatus</code>.
   * MutexStatus contains which objects hold  mutex locks, and which objects this workflow is waiting on to release locks.
   * @alias module:model/IoArgoprojWorkflowV1alpha1MutexStatus
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1MutexStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1MutexStatus} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1MutexStatus} The populated <code>IoArgoprojWorkflowV1alpha1MutexStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1MutexStatus();
      if (data.hasOwnProperty('holding'))
        obj.holding = ApiClient.convertToType(data['holding'], [IoArgoprojWorkflowV1alpha1MutexHolding]);
      if (data.hasOwnProperty('waiting'))
        obj.waiting = ApiClient.convertToType(data['waiting'], [IoArgoprojWorkflowV1alpha1MutexHolding]);
    }
    return obj;
  }
}

/**
 * Holding is a list of mutexes and their respective objects that are held by mutex lock for this io.argoproj.workflow.v1alpha1.
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1MutexHolding>} holding
 */
IoArgoprojWorkflowV1alpha1MutexStatus.prototype.holding = undefined;

/**
 * Waiting is a list of mutexes and their respective objects this workflow is waiting for.
 * @member {Array.<module:model/IoArgoprojWorkflowV1alpha1MutexHolding>} waiting
 */
IoArgoprojWorkflowV1alpha1MutexStatus.prototype.waiting = undefined;

module.exports = IoArgoprojWorkflowV1alpha1MutexStatus;
