/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1SecretKeySelector = require('./IoK8sApiCoreV1SecretKeySelector');

/**
 * The IoArgoprojWorkflowV1alpha1AzureArtifactRepository model module.
 * @module model/IoArgoprojWorkflowV1alpha1AzureArtifactRepository
 * @version VERSION
 */
class IoArgoprojWorkflowV1alpha1AzureArtifactRepository {
  /**
   * Constructs a new <code>IoArgoprojWorkflowV1alpha1AzureArtifactRepository</code>.
   * AzureArtifactRepository defines the controller configuration for an Azure Blob Storage artifact repository
   * @alias module:model/IoArgoprojWorkflowV1alpha1AzureArtifactRepository
   * @class
   * @param container {String} Container is the container where resources will be stored
   * @param endpoint {String} Endpoint is the service url associated with an account. It is most likely \"https://<ACCOUNT_NAME>.blob.core.windows.net\"
   */
  constructor(container, endpoint) {
    this.container = container;
    this.endpoint = endpoint;
  }

  /**
   * Constructs a <code>IoArgoprojWorkflowV1alpha1AzureArtifactRepository</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoArgoprojWorkflowV1alpha1AzureArtifactRepository} obj Optional instance to populate.
   * @return {module:model/IoArgoprojWorkflowV1alpha1AzureArtifactRepository} The populated <code>IoArgoprojWorkflowV1alpha1AzureArtifactRepository</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoArgoprojWorkflowV1alpha1AzureArtifactRepository();
      if (data.hasOwnProperty('accountKeySecret'))
        obj.accountKeySecret = IoK8sApiCoreV1SecretKeySelector.constructFromObject(data['accountKeySecret']);
      if (data.hasOwnProperty('blobNameFormat'))
        obj.blobNameFormat = ApiClient.convertToType(data['blobNameFormat'], 'String');
      if (data.hasOwnProperty('container'))
        obj.container = ApiClient.convertToType(data['container'], 'String');
      if (data.hasOwnProperty('endpoint'))
        obj.endpoint = ApiClient.convertToType(data['endpoint'], 'String');
      if (data.hasOwnProperty('useSDKCreds'))
        obj.useSDKCreds = ApiClient.convertToType(data['useSDKCreds'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1SecretKeySelector} accountKeySecret
 */
IoArgoprojWorkflowV1alpha1AzureArtifactRepository.prototype.accountKeySecret = undefined;

/**
 * BlobNameFormat is defines the format of how to store blob names. Can reference workflow variables
 * @member {String} blobNameFormat
 */
IoArgoprojWorkflowV1alpha1AzureArtifactRepository.prototype.blobNameFormat = undefined;

/**
 * Container is the container where resources will be stored
 * @member {String} container
 */
IoArgoprojWorkflowV1alpha1AzureArtifactRepository.prototype.container = undefined;

/**
 * Endpoint is the service url associated with an account. It is most likely \"https://<ACCOUNT_NAME>.blob.core.windows.net\"
 * @member {String} endpoint
 */
IoArgoprojWorkflowV1alpha1AzureArtifactRepository.prototype.endpoint = undefined;

/**
 * UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
 * @member {Boolean} useSDKCreds
 */
IoArgoprojWorkflowV1alpha1AzureArtifactRepository.prototype.useSDKCreds = undefined;

module.exports = IoArgoprojWorkflowV1alpha1AzureArtifactRepository;
