/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApimachineryPkgUtilIntstrIntOrString = require('./IoK8sApimachineryPkgUtilIntstrIntOrString');

/**
 * The IoK8sApiCoreV1TCPSocketAction model module.
 * @module model/IoK8sApiCoreV1TCPSocketAction
 * @version VERSION
 */
class IoK8sApiCoreV1TCPSocketAction {
  /**
   * Constructs a new <code>IoK8sApiCoreV1TCPSocketAction</code>.
   * TCPSocketAction describes an action based on opening a socket
   * @alias module:model/IoK8sApiCoreV1TCPSocketAction
   * @class
   * @param port {module:model/IoK8sApimachineryPkgUtilIntstrIntOrString} 
   */
  constructor(port) {
    this.port = port;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1TCPSocketAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1TCPSocketAction} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1TCPSocketAction} The populated <code>IoK8sApiCoreV1TCPSocketAction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1TCPSocketAction();
      if (data.hasOwnProperty('host'))
        obj.host = ApiClient.convertToType(data['host'], 'String');
      if (data.hasOwnProperty('port'))
        obj.port = IoK8sApimachineryPkgUtilIntstrIntOrString.constructFromObject(data['port']);
    }
    return obj;
  }
}

/**
 * Optional: Host name to connect to, defaults to the pod IP.
 * @member {String} host
 */
IoK8sApiCoreV1TCPSocketAction.prototype.host = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgUtilIntstrIntOrString} port
 */
IoK8sApiCoreV1TCPSocketAction.prototype.port = undefined;

module.exports = IoK8sApiCoreV1TCPSocketAction;
