/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApimachineryPkgApisMetaV1GroupVersionResource model module.
 * @module model/IoK8sApimachineryPkgApisMetaV1GroupVersionResource
 * @version VERSION
 */
class IoK8sApimachineryPkgApisMetaV1GroupVersionResource {
  /**
   * Constructs a new <code>IoK8sApimachineryPkgApisMetaV1GroupVersionResource</code>.
   * +protobuf.options.(gogoproto.goproto_stringer)&#x3D;false
   * @alias module:model/IoK8sApimachineryPkgApisMetaV1GroupVersionResource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApimachineryPkgApisMetaV1GroupVersionResource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApimachineryPkgApisMetaV1GroupVersionResource} obj Optional instance to populate.
   * @return {module:model/IoK8sApimachineryPkgApisMetaV1GroupVersionResource} The populated <code>IoK8sApimachineryPkgApisMetaV1GroupVersionResource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApimachineryPkgApisMetaV1GroupVersionResource();
      if (data.hasOwnProperty('group'))
        obj.group = ApiClient.convertToType(data['group'], 'String');
      if (data.hasOwnProperty('resource'))
        obj.resource = ApiClient.convertToType(data['resource'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} group
 */
IoK8sApimachineryPkgApisMetaV1GroupVersionResource.prototype.group = undefined;

/**
 * @member {String} resource
 */
IoK8sApimachineryPkgApisMetaV1GroupVersionResource.prototype.resource = undefined;

/**
 * @member {String} version
 */
IoK8sApimachineryPkgApisMetaV1GroupVersionResource.prototype.version = undefined;

module.exports = IoK8sApimachineryPkgApisMetaV1GroupVersionResource;
