/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1AppArmorProfile = require('./IoK8sApiCoreV1AppArmorProfile');
const IoK8sApiCoreV1Capabilities = require('./IoK8sApiCoreV1Capabilities');
const IoK8sApiCoreV1SELinuxOptions = require('./IoK8sApiCoreV1SELinuxOptions');
const IoK8sApiCoreV1SeccompProfile = require('./IoK8sApiCoreV1SeccompProfile');
const IoK8sApiCoreV1WindowsSecurityContextOptions = require('./IoK8sApiCoreV1WindowsSecurityContextOptions');

/**
 * The IoK8sApiCoreV1SecurityContext model module.
 * @module model/IoK8sApiCoreV1SecurityContext
 * @version VERSION
 */
class IoK8sApiCoreV1SecurityContext {
  /**
   * Constructs a new <code>IoK8sApiCoreV1SecurityContext</code>.
   * SecurityContext holds security configuration that will be applied to a container. Some fields are present in both SecurityContext and PodSecurityContext.  When both are set, the values in SecurityContext take precedence.
   * @alias module:model/IoK8sApiCoreV1SecurityContext
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1SecurityContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1SecurityContext} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1SecurityContext} The populated <code>IoK8sApiCoreV1SecurityContext</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1SecurityContext();
      if (data.hasOwnProperty('allowPrivilegeEscalation'))
        obj.allowPrivilegeEscalation = ApiClient.convertToType(data['allowPrivilegeEscalation'], 'Boolean');
      if (data.hasOwnProperty('appArmorProfile'))
        obj.appArmorProfile = IoK8sApiCoreV1AppArmorProfile.constructFromObject(data['appArmorProfile']);
      if (data.hasOwnProperty('capabilities'))
        obj.capabilities = IoK8sApiCoreV1Capabilities.constructFromObject(data['capabilities']);
      if (data.hasOwnProperty('privileged'))
        obj.privileged = ApiClient.convertToType(data['privileged'], 'Boolean');
      if (data.hasOwnProperty('procMount'))
        obj.procMount = ApiClient.convertToType(data['procMount'], 'String');
      if (data.hasOwnProperty('readOnlyRootFilesystem'))
        obj.readOnlyRootFilesystem = ApiClient.convertToType(data['readOnlyRootFilesystem'], 'Boolean');
      if (data.hasOwnProperty('runAsGroup'))
        obj.runAsGroup = ApiClient.convertToType(data['runAsGroup'], 'Number');
      if (data.hasOwnProperty('runAsNonRoot'))
        obj.runAsNonRoot = ApiClient.convertToType(data['runAsNonRoot'], 'Boolean');
      if (data.hasOwnProperty('runAsUser'))
        obj.runAsUser = ApiClient.convertToType(data['runAsUser'], 'Number');
      if (data.hasOwnProperty('seLinuxOptions'))
        obj.seLinuxOptions = IoK8sApiCoreV1SELinuxOptions.constructFromObject(data['seLinuxOptions']);
      if (data.hasOwnProperty('seccompProfile'))
        obj.seccompProfile = IoK8sApiCoreV1SeccompProfile.constructFromObject(data['seccompProfile']);
      if (data.hasOwnProperty('windowsOptions'))
        obj.windowsOptions = IoK8sApiCoreV1WindowsSecurityContextOptions.constructFromObject(data['windowsOptions']);
    }
    return obj;
  }
}

/**
 * AllowPrivilegeEscalation controls whether a process can gain more privileges than its parent process. This bool directly controls if the no_new_privs flag will be set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN Note that this field cannot be set when spec.os.name is windows.
 * @member {Boolean} allowPrivilegeEscalation
 */
IoK8sApiCoreV1SecurityContext.prototype.allowPrivilegeEscalation = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1AppArmorProfile} appArmorProfile
 */
IoK8sApiCoreV1SecurityContext.prototype.appArmorProfile = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1Capabilities} capabilities
 */
IoK8sApiCoreV1SecurityContext.prototype.capabilities = undefined;

/**
 * Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false. Note that this field cannot be set when spec.os.name is windows.
 * @member {Boolean} privileged
 */
IoK8sApiCoreV1SecurityContext.prototype.privileged = undefined;

/**
 * procMount denotes the type of proc mount to use for the containers. The default value is Default which uses the container runtime defaults for readonly paths and masked paths. This requires the ProcMountType feature flag to be enabled. Note that this field cannot be set when spec.os.name is windows.
 * @member {String} procMount
 */
IoK8sApiCoreV1SecurityContext.prototype.procMount = undefined;

/**
 * Whether this container has a read-only root filesystem. Default is false. Note that this field cannot be set when spec.os.name is windows.
 * @member {Boolean} readOnlyRootFilesystem
 */
IoK8sApiCoreV1SecurityContext.prototype.readOnlyRootFilesystem = undefined;

/**
 * The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
 * @member {Number} runAsGroup
 */
IoK8sApiCoreV1SecurityContext.prototype.runAsGroup = undefined;

/**
 * Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
 * @member {Boolean} runAsNonRoot
 */
IoK8sApiCoreV1SecurityContext.prototype.runAsNonRoot = undefined;

/**
 * The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is windows.
 * @member {Number} runAsUser
 */
IoK8sApiCoreV1SecurityContext.prototype.runAsUser = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SELinuxOptions} seLinuxOptions
 */
IoK8sApiCoreV1SecurityContext.prototype.seLinuxOptions = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1SeccompProfile} seccompProfile
 */
IoK8sApiCoreV1SecurityContext.prototype.seccompProfile = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1WindowsSecurityContextOptions} windowsOptions
 */
IoK8sApiCoreV1SecurityContext.prototype.windowsOptions = undefined;

module.exports = IoK8sApiCoreV1SecurityContext;
