/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApimachineryPkgApisMetaV1ListMeta model module.
 * @module model/IoK8sApimachineryPkgApisMetaV1ListMeta
 * @version VERSION
 */
class IoK8sApimachineryPkgApisMetaV1ListMeta {
  /**
   * Constructs a new <code>IoK8sApimachineryPkgApisMetaV1ListMeta</code>.
   * ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
   * @alias module:model/IoK8sApimachineryPkgApisMetaV1ListMeta
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApimachineryPkgApisMetaV1ListMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApimachineryPkgApisMetaV1ListMeta} obj Optional instance to populate.
   * @return {module:model/IoK8sApimachineryPkgApisMetaV1ListMeta} The populated <code>IoK8sApimachineryPkgApisMetaV1ListMeta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApimachineryPkgApisMetaV1ListMeta();
      if (data.hasOwnProperty('continue'))
        obj._continue = ApiClient.convertToType(data['continue'], 'String');
      if (data.hasOwnProperty('remainingItemCount'))
        obj.remainingItemCount = ApiClient.convertToType(data['remainingItemCount'], 'Number');
      if (data.hasOwnProperty('resourceVersion'))
        obj.resourceVersion = ApiClient.convertToType(data['resourceVersion'], 'String');
      if (data.hasOwnProperty('selfLink'))
        obj.selfLink = ApiClient.convertToType(data['selfLink'], 'String');
    }
    return obj;
  }
}

/**
 * continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message.
 * @member {String} _continue
 */
IoK8sApimachineryPkgApisMetaV1ListMeta.prototype._continue = undefined;

/**
 * remainingItemCount is the number of subsequent items in the list which are not included in this list response. If the list request contained label or field selectors, then the number of remaining items is unknown and the field will be left unset and omitted during serialization. If the list is complete (either because it is not chunking or because this is the last chunk), then there are no more remaining items and this field will be left unset and omitted during serialization. Servers older than v1.15 do not set this field. The intended use of the remainingItemCount is *estimating* the size of a collection. Clients should not rely on the remainingItemCount to be set or to be exact.
 * @member {Number} remainingItemCount
 */
IoK8sApimachineryPkgApisMetaV1ListMeta.prototype.remainingItemCount = undefined;

/**
 * String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
 * @member {String} resourceVersion
 */
IoK8sApimachineryPkgApisMetaV1ListMeta.prototype.resourceVersion = undefined;

/**
 * Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
 * @member {String} selfLink
 */
IoK8sApimachineryPkgApisMetaV1ListMeta.prototype.selfLink = undefined;

module.exports = IoK8sApimachineryPkgApisMetaV1ListMeta;
