/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApiCoreV1ConfigMapEnvSource model module.
 * @module model/IoK8sApiCoreV1ConfigMapEnvSource
 * @version VERSION
 */
class IoK8sApiCoreV1ConfigMapEnvSource {
  /**
   * Constructs a new <code>IoK8sApiCoreV1ConfigMapEnvSource</code>.
   * ConfigMapEnvSource selects a ConfigMap to populate the environment variables with.  The contents of the target ConfigMap&#x27;s Data field will represent the key-value pairs as environment variables.
   * @alias module:model/IoK8sApiCoreV1ConfigMapEnvSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1ConfigMapEnvSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1ConfigMapEnvSource} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1ConfigMapEnvSource} The populated <code>IoK8sApiCoreV1ConfigMapEnvSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1ConfigMapEnvSource();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('optional'))
        obj.optional = ApiClient.convertToType(data['optional'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
 * @member {String} name
 */
IoK8sApiCoreV1ConfigMapEnvSource.prototype.name = undefined;

/**
 * Specify whether the ConfigMap must be defined
 * @member {Boolean} optional
 */
IoK8sApiCoreV1ConfigMapEnvSource.prototype.optional = undefined;

module.exports = IoK8sApiCoreV1ConfigMapEnvSource;
