/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1PersistentVolumeClaimTemplate = require('./IoK8sApiCoreV1PersistentVolumeClaimTemplate');

/**
 * The IoK8sApiCoreV1EphemeralVolumeSource model module.
 * @module model/IoK8sApiCoreV1EphemeralVolumeSource
 * @version VERSION
 */
class IoK8sApiCoreV1EphemeralVolumeSource {
  /**
   * Constructs a new <code>IoK8sApiCoreV1EphemeralVolumeSource</code>.
   * Represents an ephemeral volume that is handled by a normal storage driver.
   * @alias module:model/IoK8sApiCoreV1EphemeralVolumeSource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1EphemeralVolumeSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1EphemeralVolumeSource} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1EphemeralVolumeSource} The populated <code>IoK8sApiCoreV1EphemeralVolumeSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1EphemeralVolumeSource();
      if (data.hasOwnProperty('volumeClaimTemplate'))
        obj.volumeClaimTemplate = IoK8sApiCoreV1PersistentVolumeClaimTemplate.constructFromObject(data['volumeClaimTemplate']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1PersistentVolumeClaimTemplate} volumeClaimTemplate
 */
IoK8sApiCoreV1EphemeralVolumeSource.prototype.volumeClaimTemplate = undefined;

module.exports = IoK8sApiCoreV1EphemeralVolumeSource;
