/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApimachineryPkgApisMetaV1MicroTime = require('./IoK8sApimachineryPkgApisMetaV1MicroTime');

/**
 * The IoK8sApiCoreV1EventSeries model module.
 * @module model/IoK8sApiCoreV1EventSeries
 * @version VERSION
 */
class IoK8sApiCoreV1EventSeries {
  /**
   * Constructs a new <code>IoK8sApiCoreV1EventSeries</code>.
   * EventSeries contain information on series of events, i.e. thing that was/is happening continuously for some time.
   * @alias module:model/IoK8sApiCoreV1EventSeries
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1EventSeries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1EventSeries} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1EventSeries} The populated <code>IoK8sApiCoreV1EventSeries</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1EventSeries();
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
      if (data.hasOwnProperty('lastObservedTime'))
        obj.lastObservedTime = IoK8sApimachineryPkgApisMetaV1MicroTime.constructFromObject(data['lastObservedTime']);
    }
    return obj;
  }
}

/**
 * Number of occurrences in this series up to the last heartbeat time
 * @member {Number} count
 */
IoK8sApiCoreV1EventSeries.prototype.count = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1MicroTime} lastObservedTime
 */
IoK8sApiCoreV1EventSeries.prototype.lastObservedTime = undefined;

module.exports = IoK8sApiCoreV1EventSeries;
