/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApiCoreV1AzureFileVolumeSource model module.
 * @module model/IoK8sApiCoreV1AzureFileVolumeSource
 * @version VERSION
 */
class IoK8sApiCoreV1AzureFileVolumeSource {
  /**
   * Constructs a new <code>IoK8sApiCoreV1AzureFileVolumeSource</code>.
   * AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
   * @alias module:model/IoK8sApiCoreV1AzureFileVolumeSource
   * @class
   * @param secretName {String} secretName is the  name of secret that contains Azure Storage Account Name and Key
   * @param shareName {String} shareName is the azure share Name
   */
  constructor(secretName, shareName) {
    this.secretName = secretName;
    this.shareName = shareName;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1AzureFileVolumeSource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1AzureFileVolumeSource} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1AzureFileVolumeSource} The populated <code>IoK8sApiCoreV1AzureFileVolumeSource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1AzureFileVolumeSource();
      if (data.hasOwnProperty('readOnly'))
        obj.readOnly = ApiClient.convertToType(data['readOnly'], 'Boolean');
      if (data.hasOwnProperty('secretName'))
        obj.secretName = ApiClient.convertToType(data['secretName'], 'String');
      if (data.hasOwnProperty('shareName'))
        obj.shareName = ApiClient.convertToType(data['shareName'], 'String');
    }
    return obj;
  }
}

/**
 * readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 * @member {Boolean} readOnly
 */
IoK8sApiCoreV1AzureFileVolumeSource.prototype.readOnly = undefined;

/**
 * secretName is the  name of secret that contains Azure Storage Account Name and Key
 * @member {String} secretName
 */
IoK8sApiCoreV1AzureFileVolumeSource.prototype.secretName = undefined;

/**
 * shareName is the azure share Name
 * @member {String} shareName
 */
IoK8sApiCoreV1AzureFileVolumeSource.prototype.shareName = undefined;

module.exports = IoK8sApiCoreV1AzureFileVolumeSource;
