/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApiCoreV1ModifyVolumeStatus model module.
 * @module model/IoK8sApiCoreV1ModifyVolumeStatus
 * @version VERSION
 */
class IoK8sApiCoreV1ModifyVolumeStatus {
  /**
   * Constructs a new <code>IoK8sApiCoreV1ModifyVolumeStatus</code>.
   * ModifyVolumeStatus represents the status object of ControllerModifyVolume operation
   * @alias module:model/IoK8sApiCoreV1ModifyVolumeStatus
   * @class
   * @param status {String} status is the status of the ControllerModifyVolume operation. It can be in any of following states:  - Pending    Pending indicates that the PersistentVolumeClaim cannot be modified due to unmet requirements, such as    the specified VolumeAttributesClass not existing.  - InProgress    InProgress indicates that the volume is being modified.  - Infeasible   Infeasible indicates that the request has been rejected as invalid by the CSI driver. To    resolve the error, a valid VolumeAttributesClass needs to be specified. Note: New statuses can be added in the future. Consumers should check for unknown statuses and fail appropriately.
   */
  constructor(status) {
    this.status = status;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1ModifyVolumeStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1ModifyVolumeStatus} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1ModifyVolumeStatus} The populated <code>IoK8sApiCoreV1ModifyVolumeStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1ModifyVolumeStatus();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('targetVolumeAttributesClassName'))
        obj.targetVolumeAttributesClassName = ApiClient.convertToType(data['targetVolumeAttributesClassName'], 'String');
    }
    return obj;
  }
}

/**
 * status is the status of the ControllerModifyVolume operation. It can be in any of following states:  - Pending    Pending indicates that the PersistentVolumeClaim cannot be modified due to unmet requirements, such as    the specified VolumeAttributesClass not existing.  - InProgress    InProgress indicates that the volume is being modified.  - Infeasible   Infeasible indicates that the request has been rejected as invalid by the CSI driver. To    resolve the error, a valid VolumeAttributesClass needs to be specified. Note: New statuses can be added in the future. Consumers should check for unknown statuses and fail appropriately.
 * @member {String} status
 */
IoK8sApiCoreV1ModifyVolumeStatus.prototype.status = undefined;

/**
 * targetVolumeAttributesClassName is the name of the VolumeAttributesClass the PVC currently being reconciled
 * @member {String} targetVolumeAttributesClassName
 */
IoK8sApiCoreV1ModifyVolumeStatus.prototype.targetVolumeAttributesClassName = undefined;

module.exports = IoK8sApiCoreV1ModifyVolumeStatus;
