/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApiCoreV1SecretKeySelector model module.
 * @module model/IoK8sApiCoreV1SecretKeySelector
 * @version VERSION
 */
class IoK8sApiCoreV1SecretKeySelector {
  /**
   * Constructs a new <code>IoK8sApiCoreV1SecretKeySelector</code>.
   * SecretKeySelector selects a key of a Secret.
   * @alias module:model/IoK8sApiCoreV1SecretKeySelector
   * @class
   * @param key {String} The key of the secret to select from.  Must be a valid secret key.
   */
  constructor(key) {
    this.key = key;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1SecretKeySelector</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1SecretKeySelector} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1SecretKeySelector} The populated <code>IoK8sApiCoreV1SecretKeySelector</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1SecretKeySelector();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('optional'))
        obj.optional = ApiClient.convertToType(data['optional'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The key of the secret to select from.  Must be a valid secret key.
 * @member {String} key
 */
IoK8sApiCoreV1SecretKeySelector.prototype.key = undefined;

/**
 * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
 * @member {String} name
 */
IoK8sApiCoreV1SecretKeySelector.prototype.name = undefined;

/**
 * Specify whether the Secret or its key must be defined
 * @member {Boolean} optional
 */
IoK8sApiCoreV1SecretKeySelector.prototype.optional = undefined;

module.exports = IoK8sApiCoreV1SecretKeySelector;
