/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApimachineryPkgApiResourceQuantity = require('./IoK8sApimachineryPkgApiResourceQuantity');

/**
 * The IoK8sApiCoreV1ResourceFieldSelector model module.
 * @module model/IoK8sApiCoreV1ResourceFieldSelector
 * @version VERSION
 */
class IoK8sApiCoreV1ResourceFieldSelector {
  /**
   * Constructs a new <code>IoK8sApiCoreV1ResourceFieldSelector</code>.
   * ResourceFieldSelector represents container resources (cpu, memory) and their output format
   * @alias module:model/IoK8sApiCoreV1ResourceFieldSelector
   * @class
   * @param resource {String} Required: resource to select
   */
  constructor(resource) {
    this.resource = resource;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1ResourceFieldSelector</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1ResourceFieldSelector} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1ResourceFieldSelector} The populated <code>IoK8sApiCoreV1ResourceFieldSelector</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1ResourceFieldSelector();
      if (data.hasOwnProperty('containerName'))
        obj.containerName = ApiClient.convertToType(data['containerName'], 'String');
      if (data.hasOwnProperty('divisor'))
        obj.divisor = IoK8sApimachineryPkgApiResourceQuantity.constructFromObject(data['divisor']);
      if (data.hasOwnProperty('resource'))
        obj.resource = ApiClient.convertToType(data['resource'], 'String');
    }
    return obj;
  }
}

/**
 * Container name: required for volumes, optional for env vars
 * @member {String} containerName
 */
IoK8sApiCoreV1ResourceFieldSelector.prototype.containerName = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgApiResourceQuantity} divisor
 */
IoK8sApiCoreV1ResourceFieldSelector.prototype.divisor = undefined;

/**
 * Required: resource to select
 * @member {String} resource
 */
IoK8sApiCoreV1ResourceFieldSelector.prototype.resource = undefined;

module.exports = IoK8sApiCoreV1ResourceFieldSelector;
