/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApimachineryPkgApisMetaV1CreateOptions model module.
 * @module model/IoK8sApimachineryPkgApisMetaV1CreateOptions
 * @version VERSION
 */
class IoK8sApimachineryPkgApisMetaV1CreateOptions {
  /**
   * Constructs a new <code>IoK8sApimachineryPkgApisMetaV1CreateOptions</code>.
   * CreateOptions may be provided when creating an API object.
   * @alias module:model/IoK8sApimachineryPkgApisMetaV1CreateOptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApimachineryPkgApisMetaV1CreateOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApimachineryPkgApisMetaV1CreateOptions} obj Optional instance to populate.
   * @return {module:model/IoK8sApimachineryPkgApisMetaV1CreateOptions} The populated <code>IoK8sApimachineryPkgApisMetaV1CreateOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApimachineryPkgApisMetaV1CreateOptions();
      if (data.hasOwnProperty('dryRun'))
        obj.dryRun = ApiClient.convertToType(data['dryRun'], ['String']);
      if (data.hasOwnProperty('fieldManager'))
        obj.fieldManager = ApiClient.convertToType(data['fieldManager'], 'String');
      if (data.hasOwnProperty('fieldValidation'))
        obj.fieldValidation = ApiClient.convertToType(data['fieldValidation'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} dryRun
 */
IoK8sApimachineryPkgApisMetaV1CreateOptions.prototype.dryRun = undefined;

/**
 * @member {String} fieldManager
 */
IoK8sApimachineryPkgApisMetaV1CreateOptions.prototype.fieldManager = undefined;

/**
 * @member {String} fieldValidation
 */
IoK8sApimachineryPkgApisMetaV1CreateOptions.prototype.fieldValidation = undefined;

module.exports = IoK8sApimachineryPkgApisMetaV1CreateOptions;
