/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1LifecycleHandler = require('./IoK8sApiCoreV1LifecycleHandler');

/**
 * The IoK8sApiCoreV1Lifecycle model module.
 * @module model/IoK8sApiCoreV1Lifecycle
 * @version VERSION
 */
class IoK8sApiCoreV1Lifecycle {
  /**
   * Constructs a new <code>IoK8sApiCoreV1Lifecycle</code>.
   * Lifecycle describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted.
   * @alias module:model/IoK8sApiCoreV1Lifecycle
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1Lifecycle</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1Lifecycle} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1Lifecycle} The populated <code>IoK8sApiCoreV1Lifecycle</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1Lifecycle();
      if (data.hasOwnProperty('postStart'))
        obj.postStart = IoK8sApiCoreV1LifecycleHandler.constructFromObject(data['postStart']);
      if (data.hasOwnProperty('preStop'))
        obj.preStop = IoK8sApiCoreV1LifecycleHandler.constructFromObject(data['preStop']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1LifecycleHandler} postStart
 */
IoK8sApiCoreV1Lifecycle.prototype.postStart = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1LifecycleHandler} preStop
 */
IoK8sApiCoreV1Lifecycle.prototype.preStop = undefined;

module.exports = IoK8sApiCoreV1Lifecycle;
