/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1ObjectFieldSelector = require('./IoK8sApiCoreV1ObjectFieldSelector');
const IoK8sApiCoreV1ResourceFieldSelector = require('./IoK8sApiCoreV1ResourceFieldSelector');

/**
 * The IoK8sApiCoreV1DownwardAPIVolumeFile model module.
 * @module model/IoK8sApiCoreV1DownwardAPIVolumeFile
 * @version VERSION
 */
class IoK8sApiCoreV1DownwardAPIVolumeFile {
  /**
   * Constructs a new <code>IoK8sApiCoreV1DownwardAPIVolumeFile</code>.
   * DownwardAPIVolumeFile represents information to create the file containing the pod field
   * @alias module:model/IoK8sApiCoreV1DownwardAPIVolumeFile
   * @class
   * @param path {String} Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'
   */
  constructor(path) {
    this.path = path;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1DownwardAPIVolumeFile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1DownwardAPIVolumeFile} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1DownwardAPIVolumeFile} The populated <code>IoK8sApiCoreV1DownwardAPIVolumeFile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1DownwardAPIVolumeFile();
      if (data.hasOwnProperty('fieldRef'))
        obj.fieldRef = IoK8sApiCoreV1ObjectFieldSelector.constructFromObject(data['fieldRef']);
      if (data.hasOwnProperty('mode'))
        obj.mode = ApiClient.convertToType(data['mode'], 'Number');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('resourceFieldRef'))
        obj.resourceFieldRef = IoK8sApiCoreV1ResourceFieldSelector.constructFromObject(data['resourceFieldRef']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApiCoreV1ObjectFieldSelector} fieldRef
 */
IoK8sApiCoreV1DownwardAPIVolumeFile.prototype.fieldRef = undefined;

/**
 * Optional: mode bits used to set permissions on this file, must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
 * @member {Number} mode
 */
IoK8sApiCoreV1DownwardAPIVolumeFile.prototype.mode = undefined;

/**
 * Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'
 * @member {String} path
 */
IoK8sApiCoreV1DownwardAPIVolumeFile.prototype.path = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1ResourceFieldSelector} resourceFieldRef
 */
IoK8sApiCoreV1DownwardAPIVolumeFile.prototype.resourceFieldRef = undefined;

module.exports = IoK8sApiCoreV1DownwardAPIVolumeFile;
