/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApiCoreV1SleepAction model module.
 * @module model/IoK8sApiCoreV1SleepAction
 * @version VERSION
 */
class IoK8sApiCoreV1SleepAction {
  /**
   * Constructs a new <code>IoK8sApiCoreV1SleepAction</code>.
   * SleepAction describes a \&quot;sleep\&quot; action.
   * @alias module:model/IoK8sApiCoreV1SleepAction
   * @class
   * @param seconds {Number} Seconds is the number of seconds to sleep.
   */
  constructor(seconds) {
    this.seconds = seconds;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1SleepAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1SleepAction} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1SleepAction} The populated <code>IoK8sApiCoreV1SleepAction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1SleepAction();
      if (data.hasOwnProperty('seconds'))
        obj.seconds = ApiClient.convertToType(data['seconds'], 'Number');
    }
    return obj;
  }
}

/**
 * Seconds is the number of seconds to sleep.
 * @member {Number} seconds
 */
IoK8sApiCoreV1SleepAction.prototype.seconds = undefined;

module.exports = IoK8sApiCoreV1SleepAction;
