/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApimachineryPkgApisMetaV1Time = require('./IoK8sApimachineryPkgApisMetaV1Time');

/**
 * The IoK8sApiCoreV1PersistentVolumeClaimCondition model module.
 * @module model/IoK8sApiCoreV1PersistentVolumeClaimCondition
 * @version VERSION
 */
class IoK8sApiCoreV1PersistentVolumeClaimCondition {
  /**
   * Constructs a new <code>IoK8sApiCoreV1PersistentVolumeClaimCondition</code>.
   * PersistentVolumeClaimCondition contains details about state of pvc
   * @alias module:model/IoK8sApiCoreV1PersistentVolumeClaimCondition
   * @class
   * @param status {String} 
   * @param type {String} 
   */
  constructor(status, type) {
    this.status = status;
    this.type = type;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1PersistentVolumeClaimCondition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1PersistentVolumeClaimCondition} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1PersistentVolumeClaimCondition} The populated <code>IoK8sApiCoreV1PersistentVolumeClaimCondition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1PersistentVolumeClaimCondition();
      if (data.hasOwnProperty('lastProbeTime'))
        obj.lastProbeTime = IoK8sApimachineryPkgApisMetaV1Time.constructFromObject(data['lastProbeTime']);
      if (data.hasOwnProperty('lastTransitionTime'))
        obj.lastTransitionTime = IoK8sApimachineryPkgApisMetaV1Time.constructFromObject(data['lastTransitionTime']);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('reason'))
        obj.reason = ApiClient.convertToType(data['reason'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1Time} lastProbeTime
 */
IoK8sApiCoreV1PersistentVolumeClaimCondition.prototype.lastProbeTime = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1Time} lastTransitionTime
 */
IoK8sApiCoreV1PersistentVolumeClaimCondition.prototype.lastTransitionTime = undefined;

/**
 * message is the human-readable message indicating details about last transition.
 * @member {String} message
 */
IoK8sApiCoreV1PersistentVolumeClaimCondition.prototype.message = undefined;

/**
 * reason is a unique, this should be a short, machine understandable string that gives the reason for condition's last transition. If it reports \"Resizing\" that means the underlying persistent volume is being resized.
 * @member {String} reason
 */
IoK8sApiCoreV1PersistentVolumeClaimCondition.prototype.reason = undefined;

/**
 * @member {String} status
 */
IoK8sApiCoreV1PersistentVolumeClaimCondition.prototype.status = undefined;

/**
 * @member {String} type
 */
IoK8sApiCoreV1PersistentVolumeClaimCondition.prototype.type = undefined;

module.exports = IoK8sApiCoreV1PersistentVolumeClaimCondition;
