/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoK8sApiCoreV1PersistentVolumeClaimSpec = require('./IoK8sApiCoreV1PersistentVolumeClaimSpec');
const IoK8sApiCoreV1PersistentVolumeClaimStatus = require('./IoK8sApiCoreV1PersistentVolumeClaimStatus');
const IoK8sApimachineryPkgApisMetaV1ObjectMeta = require('./IoK8sApimachineryPkgApisMetaV1ObjectMeta');

/**
 * The IoK8sApiCoreV1PersistentVolumeClaim model module.
 * @module model/IoK8sApiCoreV1PersistentVolumeClaim
 * @version VERSION
 */
class IoK8sApiCoreV1PersistentVolumeClaim {
  /**
   * Constructs a new <code>IoK8sApiCoreV1PersistentVolumeClaim</code>.
   * PersistentVolumeClaim is a user&#x27;s request for and claim to a persistent volume
   * @alias module:model/IoK8sApiCoreV1PersistentVolumeClaim
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1PersistentVolumeClaim</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1PersistentVolumeClaim} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1PersistentVolumeClaim} The populated <code>IoK8sApiCoreV1PersistentVolumeClaim</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1PersistentVolumeClaim();
      if (data.hasOwnProperty('apiVersion'))
        obj.apiVersion = ApiClient.convertToType(data['apiVersion'], 'String');
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], 'String');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = IoK8sApimachineryPkgApisMetaV1ObjectMeta.constructFromObject(data['metadata']);
      if (data.hasOwnProperty('spec'))
        obj.spec = IoK8sApiCoreV1PersistentVolumeClaimSpec.constructFromObject(data['spec']);
      if (data.hasOwnProperty('status'))
        obj.status = IoK8sApiCoreV1PersistentVolumeClaimStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
 * @member {String} apiVersion
 */
IoK8sApiCoreV1PersistentVolumeClaim.prototype.apiVersion = undefined;

/**
 * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
 * @member {String} kind
 */
IoK8sApiCoreV1PersistentVolumeClaim.prototype.kind = undefined;

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1ObjectMeta} metadata
 */
IoK8sApiCoreV1PersistentVolumeClaim.prototype.metadata = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1PersistentVolumeClaimSpec} spec
 */
IoK8sApiCoreV1PersistentVolumeClaim.prototype.spec = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1PersistentVolumeClaimStatus} status
 */
IoK8sApiCoreV1PersistentVolumeClaim.prototype.status = undefined;

module.exports = IoK8sApiCoreV1PersistentVolumeClaim;
