/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApiCoreV1Capabilities model module.
 * @module model/IoK8sApiCoreV1Capabilities
 * @version VERSION
 */
class IoK8sApiCoreV1Capabilities {
  /**
   * Constructs a new <code>IoK8sApiCoreV1Capabilities</code>.
   * Adds and removes POSIX capabilities from running containers.
   * @alias module:model/IoK8sApiCoreV1Capabilities
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1Capabilities</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1Capabilities} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1Capabilities} The populated <code>IoK8sApiCoreV1Capabilities</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1Capabilities();
      if (data.hasOwnProperty('add'))
        obj.add = ApiClient.convertToType(data['add'], ['String']);
      if (data.hasOwnProperty('drop'))
        obj.drop = ApiClient.convertToType(data['drop'], ['String']);
    }
    return obj;
  }
}

/**
 * Added capabilities
 * @member {Array.<String>} add
 */
IoK8sApiCoreV1Capabilities.prototype.add = undefined;

/**
 * Removed capabilities
 * @member {Array.<String>} drop
 */
IoK8sApiCoreV1Capabilities.prototype.drop = undefined;

module.exports = IoK8sApiCoreV1Capabilities;
