/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The IoK8sApiCoreV1ConfigMapKeySelector model module.
 * @module model/IoK8sApiCoreV1ConfigMapKeySelector
 * @version VERSION
 */
class IoK8sApiCoreV1ConfigMapKeySelector {
  /**
   * Constructs a new <code>IoK8sApiCoreV1ConfigMapKeySelector</code>.
   * Selects a key from a ConfigMap.
   * @alias module:model/IoK8sApiCoreV1ConfigMapKeySelector
   * @class
   * @param key {String} The key to select.
   */
  constructor(key) {
    this.key = key;
  }

  /**
   * Constructs a <code>IoK8sApiCoreV1ConfigMapKeySelector</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IoK8sApiCoreV1ConfigMapKeySelector} obj Optional instance to populate.
   * @return {module:model/IoK8sApiCoreV1ConfigMapKeySelector} The populated <code>IoK8sApiCoreV1ConfigMapKeySelector</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IoK8sApiCoreV1ConfigMapKeySelector();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('optional'))
        obj.optional = ApiClient.convertToType(data['optional'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The key to select.
 * @member {String} key
 */
IoK8sApiCoreV1ConfigMapKeySelector.prototype.key = undefined;

/**
 * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
 * @member {String} name
 */
IoK8sApiCoreV1ConfigMapKeySelector.prototype.name = undefined;

/**
 * Specify whether the ConfigMap or its key must be defined
 * @member {Boolean} optional
 */
IoK8sApiCoreV1ConfigMapKeySelector.prototype.optional = undefined;

module.exports = IoK8sApiCoreV1ConfigMapKeySelector;
