/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');

/**
 * The SensorDeleteSensorResponse model module.
 * @module model/SensorDeleteSensorResponse
 * @version VERSION
 */
class SensorDeleteSensorResponse {
  /**
   * Constructs a new <code>SensorDeleteSensorResponse</code>.
   * @alias module:model/SensorDeleteSensorResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SensorDeleteSensorResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SensorDeleteSensorResponse} obj Optional instance to populate.
   * @return {module:model/SensorDeleteSensorResponse} The populated <code>SensorDeleteSensorResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SensorDeleteSensorResponse();
    }
    return obj;
  }
}

module.exports = SensorDeleteSensorResponse;
