/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const IoArgoprojEventsV1alpha1Sensor = require('./IoArgoprojEventsV1alpha1Sensor');
const IoK8sApimachineryPkgApisMetaV1CreateOptions = require('./IoK8sApimachineryPkgApisMetaV1CreateOptions');

/**
 * The SensorCreateSensorRequest model module.
 * @module model/SensorCreateSensorRequest
 * @version VERSION
 */
class SensorCreateSensorRequest {
  /**
   * Constructs a new <code>SensorCreateSensorRequest</code>.
   * @alias module:model/SensorCreateSensorRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SensorCreateSensorRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SensorCreateSensorRequest} obj Optional instance to populate.
   * @return {module:model/SensorCreateSensorRequest} The populated <code>SensorCreateSensorRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SensorCreateSensorRequest();
      if (data.hasOwnProperty('createOptions'))
        obj.createOptions = IoK8sApimachineryPkgApisMetaV1CreateOptions.constructFromObject(data['createOptions']);
      if (data.hasOwnProperty('namespace'))
        obj.namespace = ApiClient.convertToType(data['namespace'], 'String');
      if (data.hasOwnProperty('sensor'))
        obj.sensor = IoArgoprojEventsV1alpha1Sensor.constructFromObject(data['sensor']);
    }
    return obj;
  }
}

/**
 * @member {module:model/IoK8sApimachineryPkgApisMetaV1CreateOptions} createOptions
 */
SensorCreateSensorRequest.prototype.createOptions = undefined;

/**
 * @member {String} namespace
 */
SensorCreateSensorRequest.prototype.namespace = undefined;

/**
 * @member {module:model/IoArgoprojEventsV1alpha1Sensor} sensor
 */
SensorCreateSensorRequest.prototype.sensor = undefined;

module.exports = SensorCreateSensorRequest;
