/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const GrpcGatewayRuntimeStreamError = require('./GrpcGatewayRuntimeStreamError');
const SensorSensorWatchEvent = require('./SensorSensorWatchEvent');

/**
 * The StreamResultOfSensorSensorWatchEvent model module.
 * @module model/StreamResultOfSensorSensorWatchEvent
 * @version VERSION
 */
class StreamResultOfSensorSensorWatchEvent {
  /**
   * Constructs a new <code>StreamResultOfSensorSensorWatchEvent</code>.
   * @alias module:model/StreamResultOfSensorSensorWatchEvent
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StreamResultOfSensorSensorWatchEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamResultOfSensorSensorWatchEvent} obj Optional instance to populate.
   * @return {module:model/StreamResultOfSensorSensorWatchEvent} The populated <code>StreamResultOfSensorSensorWatchEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamResultOfSensorSensorWatchEvent();
      if (data.hasOwnProperty('error'))
        obj.error = GrpcGatewayRuntimeStreamError.constructFromObject(data['error']);
      if (data.hasOwnProperty('result'))
        obj.result = SensorSensorWatchEvent.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GrpcGatewayRuntimeStreamError} error
 */
StreamResultOfSensorSensorWatchEvent.prototype.error = undefined;

/**
 * @member {module:model/SensorSensorWatchEvent} result
 */
StreamResultOfSensorSensorWatchEvent.prototype.result = undefined;

module.exports = StreamResultOfSensorSensorWatchEvent;
