/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const GrpcGatewayRuntimeStreamError = require('./GrpcGatewayRuntimeStreamError');
const IoK8sApiCoreV1Event = require('./IoK8sApiCoreV1Event');

/**
 * The StreamResultOfIoK8sApiCoreV1Event model module.
 * @module model/StreamResultOfIoK8sApiCoreV1Event
 * @version VERSION
 */
class StreamResultOfIoK8sApiCoreV1Event {
  /**
   * Constructs a new <code>StreamResultOfIoK8sApiCoreV1Event</code>.
   * @alias module:model/StreamResultOfIoK8sApiCoreV1Event
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StreamResultOfIoK8sApiCoreV1Event</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamResultOfIoK8sApiCoreV1Event} obj Optional instance to populate.
   * @return {module:model/StreamResultOfIoK8sApiCoreV1Event} The populated <code>StreamResultOfIoK8sApiCoreV1Event</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamResultOfIoK8sApiCoreV1Event();
      if (data.hasOwnProperty('error'))
        obj.error = GrpcGatewayRuntimeStreamError.constructFromObject(data['error']);
      if (data.hasOwnProperty('result'))
        obj.result = IoK8sApiCoreV1Event.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GrpcGatewayRuntimeStreamError} error
 */
StreamResultOfIoK8sApiCoreV1Event.prototype.error = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1Event} result
 */
StreamResultOfIoK8sApiCoreV1Event.prototype.result = undefined;

module.exports = StreamResultOfIoK8sApiCoreV1Event;
