/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * OpenAPI spec version: VERSION
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */
const ApiClient = require('../ApiClient');
const GrpcGatewayRuntimeStreamError = require('./GrpcGatewayRuntimeStreamError');
const IoArgoprojWorkflowV1alpha1WorkflowWatchEvent = require('./IoArgoprojWorkflowV1alpha1WorkflowWatchEvent');

/**
 * The StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent model module.
 * @module model/StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent
 * @version VERSION
 */
class StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent {
  /**
   * Constructs a new <code>StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent</code>.
   * @alias module:model/StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent} obj Optional instance to populate.
   * @return {module:model/StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent} The populated <code>StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent();
      if (data.hasOwnProperty('error'))
        obj.error = GrpcGatewayRuntimeStreamError.constructFromObject(data['error']);
      if (data.hasOwnProperty('result'))
        obj.result = IoArgoprojWorkflowV1alpha1WorkflowWatchEvent.constructFromObject(data['result']);
    }
    return obj;
  }
}

/**
 * @member {module:model/GrpcGatewayRuntimeStreamError} error
 */
StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.prototype.error = undefined;

/**
 * @member {module:model/IoArgoprojWorkflowV1alpha1WorkflowWatchEvent} result
 */
StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent.prototype.result = undefined;

module.exports = StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent;
